package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.AllUser;
import org.neu.entity.AllUserExample;

@Mapper
public interface AllUserMapper {
    long countByExample(AllUserExample example);

    int deleteByExample(AllUserExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AllUser record);

    int insertSelective(AllUser record);

    List<AllUser> selectByExample(AllUserExample example);

    AllUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AllUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") AllUser record, @Param("example") AllUserExample example);

    int updateByExample(@Param("record") AllUser record, @Param("example") AllUserExample example);

    int updateByPrimaryKeySelective(AllUser record);

    int updateByPrimaryKey(AllUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") AllUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}