package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.CategoryReg;
import org.neu.entity.CategoryRegExample;

@Mapper
public interface CategoryRegMapper {
    long countByExample(CategoryRegExample example);

    int deleteByExample(CategoryRegExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CategoryReg record);

    int insertSelective(CategoryReg record);

    List<CategoryReg> selectByExample(CategoryRegExample example);

    CategoryReg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategoryReg selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") CategoryReg record, @Param("example") CategoryRegExample example);

    int updateByExample(@Param("record") CategoryReg record, @Param("example") CategoryRegExample example);

    int updateByPrimaryKeySelective(CategoryReg record);

    int updateByPrimaryKey(CategoryReg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategoryRegExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}