package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.CategoryDisease;
import org.neu.entity.CategoryDiseaseExample;

@Mapper
public interface CategoryDiseaseMapper {
    long countByExample(CategoryDiseaseExample example);

    int deleteByExample(CategoryDiseaseExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CategoryDisease record);

    int insertSelective(CategoryDisease record);

    List<CategoryDisease> selectByExample(CategoryDiseaseExample example);

    CategoryDisease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategoryDisease selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") CategoryDisease record, @Param("example") CategoryDiseaseExample example);

    int updateByExample(@Param("record") CategoryDisease record, @Param("example") CategoryDiseaseExample example);

    int updateByPrimaryKeySelective(CategoryDisease record);

    int updateByPrimaryKey(CategoryDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategoryDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}