package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.CategorySettlement;
import org.neu.entity.CategorySettlementExample;

@Mapper
public interface CategorySettlementMapper {
    long countByExample(CategorySettlementExample example);

    int deleteByExample(CategorySettlementExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CategorySettlement record);

    int insertSelective(CategorySettlement record);

    List<CategorySettlement> selectByExample(CategorySettlementExample example);

    CategorySettlement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategorySettlement selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") CategorySettlement record, @Param("example") CategorySettlementExample example);

    int updateByExample(@Param("record") CategorySettlement record, @Param("example") CategorySettlementExample example);

    int updateByPrimaryKeySelective(CategorySettlement record);

    int updateByPrimaryKey(CategorySettlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategorySettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}