package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.NonDrug;
import org.neu.entity.NonDrugExample;

@Mapper
public interface NonDrugMapper {
    long countByExample(NonDrugExample example);

    int deleteByExample(NonDrugExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(NonDrug record);

    int insertSelective(NonDrug record);

    List<NonDrug> selectByExample(NonDrugExample example);

    NonDrug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NonDrug selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") NonDrug record, @Param("example") NonDrugExample example);

    int updateByExample(@Param("record") NonDrug record, @Param("example") NonDrugExample example);

    int updateByPrimaryKeySelective(NonDrug record);

    int updateByPrimaryKey(NonDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") NonDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}