package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.PaymentDtl;
import org.neu.entity.PaymentDtlExample;

@Mapper
public interface PaymentDtlMapper {
    long countByExample(PaymentDtlExample example);

    int deleteByExample(PaymentDtlExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PaymentDtl record);

    int insertSelective(PaymentDtl record);

    List<PaymentDtl> selectByExample(PaymentDtlExample example);

    PaymentDtl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PaymentDtl selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PaymentDtl record, @Param("example") PaymentDtlExample example);

    int updateByExample(@Param("record") PaymentDtl record, @Param("example") PaymentDtlExample example);

    int updateByPrimaryKeySelective(PaymentDtl record);

    int updateByPrimaryKey(PaymentDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PaymentDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}