package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.PrescriptionHerbDtl;
import org.neu.entity.PrescriptionHerbDtlExample;

@Mapper
public interface PrescriptionHerbDtlMapper {
    long countByExample(PrescriptionHerbDtlExample example);

    int deleteByExample(PrescriptionHerbDtlExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PrescriptionHerbDtl record);

    int insertSelective(PrescriptionHerbDtl record);

    List<PrescriptionHerbDtl> selectByExample(PrescriptionHerbDtlExample example);

    PrescriptionHerbDtl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PrescriptionHerbDtl selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PrescriptionHerbDtl record, @Param("example") PrescriptionHerbDtlExample example);

    int updateByExample(@Param("record") PrescriptionHerbDtl record, @Param("example") PrescriptionHerbDtlExample example);

    int updateByPrimaryKeySelective(PrescriptionHerbDtl record);

    int updateByPrimaryKey(PrescriptionHerbDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PrescriptionHerbDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}