package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.PrescriptionMedicine;
import org.neu.entity.PrescriptionMedicineExample;

@Mapper
public interface PrescriptionMedicineMapper {
    long countByExample(PrescriptionMedicineExample example);

    int deleteByExample(PrescriptionMedicineExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PrescriptionMedicine record);

    int insertSelective(PrescriptionMedicine record);

    List<PrescriptionMedicine> selectByExample(PrescriptionMedicineExample example);

    PrescriptionMedicine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PrescriptionMedicine selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PrescriptionMedicine record, @Param("example") PrescriptionMedicineExample example);

    int updateByExample(@Param("record") PrescriptionMedicine record, @Param("example") PrescriptionMedicineExample example);

    int updateByPrimaryKeySelective(PrescriptionMedicine record);

    int updateByPrimaryKey(PrescriptionMedicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PrescriptionMedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}