package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.TemplateDtlMedi;
import org.neu.entity.TemplateDtlMediExample;

@Mapper
public interface TemplateDtlMediMapper {
    long countByExample(TemplateDtlMediExample example);

    int deleteByExample(TemplateDtlMediExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TemplateDtlMedi record);

    int insertSelective(TemplateDtlMedi record);

    List<TemplateDtlMedi> selectByExample(TemplateDtlMediExample example);

    TemplateDtlMedi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateDtlMedi selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") TemplateDtlMedi record, @Param("example") TemplateDtlMediExample example);

    int updateByExample(@Param("record") TemplateDtlMedi record, @Param("example") TemplateDtlMediExample example);

    int updateByPrimaryKeySelective(TemplateDtlMedi record);

    int updateByPrimaryKey(TemplateDtlMedi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateDtlMediExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}