package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.TemplateMedi;
import org.neu.entity.TemplateMediExample;

@Mapper
public interface TemplateMediMapper {
    long countByExample(TemplateMediExample example);

    int deleteByExample(TemplateMediExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TemplateMedi record);

    int insertSelective(TemplateMedi record);

    List<TemplateMedi> selectByExample(TemplateMediExample example);

    TemplateMedi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateMedi selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") TemplateMedi record, @Param("example") TemplateMediExample example);

    int updateByExample(@Param("record") TemplateMedi record, @Param("example") TemplateMediExample example);

    int updateByPrimaryKeySelective(TemplateMedi record);

    int updateByPrimaryKey(TemplateMedi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateMediExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}