package org.neu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.entity.TemplateHerb;
import org.neu.entity.TemplateHerbExample;

@Mapper
public interface TemplateHerbMapper {
    long countByExample(TemplateHerbExample example);

    int deleteByExample(TemplateHerbExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TemplateHerb record);

    int insertSelective(TemplateHerb record);

    List<TemplateHerb> selectByExample(TemplateHerbExample example);

    TemplateHerb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateHerb selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") TemplateHerb record, @Param("example") TemplateHerbExample example);

    int updateByExample(@Param("record") TemplateHerb record, @Param("example") TemplateHerbExample example);

    int updateByPrimaryKeySelective(TemplateHerb record);

    int updateByPrimaryKey(TemplateHerb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateHerbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}