package com.neu.his.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Entity
@Table(name = "category_reg")
public class CategoryReg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    @Id
    @Column(name = "id")
    private Integer id;

    private String code;

    private String categoryName;

    private String sequence;

    private Double regAmount;

    private Integer regLimit;

    private Boolean isDeleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public CategoryReg withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public CategoryReg withCode(String code) {
        this.setCode(code);
        return this;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public CategoryReg withCategoryName(String categoryName) {
        this.setCategoryName(categoryName);
        return this;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getSequence() {
        return sequence;
    }

    public CategoryReg withSequence(String sequence) {
        this.setSequence(sequence);
        return this;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public Double getRegAmount() {
        return regAmount;
    }

    public CategoryReg withRegAmount(Double regAmount) {
        this.setRegAmount(regAmount);
        return this;
    }

    public void setRegAmount(Double regAmount) {
        this.regAmount = regAmount;
    }

    public Integer getRegLimit() {
        return regLimit;
    }

    public CategoryReg withRegLimit(Integer regLimit) {
        this.setRegLimit(regLimit);
        return this;
    }

    public void setRegLimit(Integer regLimit) {
        this.regLimit = regLimit;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public CategoryReg withIsDeleted(Boolean isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", sequence=").append(sequence);
        sb.append(", regAmount=").append(regAmount);
        sb.append(", regLimit=").append(regLimit);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CategoryReg other = (CategoryReg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCategoryName() == null ? other.getCategoryName() == null : this.getCategoryName().equals(other.getCategoryName()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getRegAmount() == null ? other.getRegAmount() == null : this.getRegAmount().equals(other.getRegAmount()))
            && (this.getRegLimit() == null ? other.getRegLimit() == null : this.getRegLimit().equals(other.getRegLimit()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCategoryName() == null) ? 0 : getCategoryName().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getRegAmount() == null) ? 0 : getRegAmount().hashCode());
        result = prime * result + ((getRegLimit() == null) ? 0 : getRegLimit().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}