package com.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class Diagnosis implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer caseId;

    private Integer regId;

    private Integer diseaseId;

    private Boolean diagnosisType;

    private Date onsetTime;

    private Boolean diagnosisClass;

    private Boolean isDeleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Diagnosis withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCaseId() {
        return caseId;
    }

    public Diagnosis withCaseId(Integer caseId) {
        this.setCaseId(caseId);
        return this;
    }

    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    public Integer getRegId() {
        return regId;
    }

    public Diagnosis withRegId(Integer regId) {
        this.setRegId(regId);
        return this;
    }

    public void setRegId(Integer regId) {
        this.regId = regId;
    }

    public Integer getDiseaseId() {
        return diseaseId;
    }

    public Diagnosis withDiseaseId(Integer diseaseId) {
        this.setDiseaseId(diseaseId);
        return this;
    }

    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    public Boolean getDiagnosisType() {
        return diagnosisType;
    }

    public Diagnosis withDiagnosisType(Boolean diagnosisType) {
        this.setDiagnosisType(diagnosisType);
        return this;
    }

    public void setDiagnosisType(Boolean diagnosisType) {
        this.diagnosisType = diagnosisType;
    }

    public Date getOnsetTime() {
        return onsetTime;
    }

    public Diagnosis withOnsetTime(Date onsetTime) {
        this.setOnsetTime(onsetTime);
        return this;
    }

    public void setOnsetTime(Date onsetTime) {
        this.onsetTime = onsetTime;
    }

    public Boolean getDiagnosisClass() {
        return diagnosisClass;
    }

    public Diagnosis withDiagnosisClass(Boolean diagnosisClass) {
        this.setDiagnosisClass(diagnosisClass);
        return this;
    }

    public void setDiagnosisClass(Boolean diagnosisClass) {
        this.diagnosisClass = diagnosisClass;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public Diagnosis withIsDeleted(Boolean isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", caseId=").append(caseId);
        sb.append(", regId=").append(regId);
        sb.append(", diseaseId=").append(diseaseId);
        sb.append(", diagnosisType=").append(diagnosisType);
        sb.append(", onsetTime=").append(onsetTime);
        sb.append(", diagnosisClass=").append(diagnosisClass);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Diagnosis other = (Diagnosis) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCaseId() == null ? other.getCaseId() == null : this.getCaseId().equals(other.getCaseId()))
            && (this.getRegId() == null ? other.getRegId() == null : this.getRegId().equals(other.getRegId()))
            && (this.getDiseaseId() == null ? other.getDiseaseId() == null : this.getDiseaseId().equals(other.getDiseaseId()))
            && (this.getDiagnosisType() == null ? other.getDiagnosisType() == null : this.getDiagnosisType().equals(other.getDiagnosisType()))
            && (this.getOnsetTime() == null ? other.getOnsetTime() == null : this.getOnsetTime().equals(other.getOnsetTime()))
            && (this.getDiagnosisClass() == null ? other.getDiagnosisClass() == null : this.getDiagnosisClass().equals(other.getDiagnosisClass()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCaseId() == null) ? 0 : getCaseId().hashCode());
        result = prime * result + ((getRegId() == null) ? 0 : getRegId().hashCode());
        result = prime * result + ((getDiseaseId() == null) ? 0 : getDiseaseId().hashCode());
        result = prime * result + ((getDiagnosisType() == null) ? 0 : getDiagnosisType().hashCode());
        result = prime * result + ((getOnsetTime() == null) ? 0 : getOnsetTime().hashCode());
        result = prime * result + ((getDiagnosisClass() == null) ? 0 : getDiagnosisClass().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}