package com.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class NonDrug implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String code;

    private String nonDrugName;

    private String standard;

    private Double unitPrice;

    private Integer categoryPaymentId;

    private Integer deptId;

    private String pinyinMnemonicCode;

    private Date createTime;

    private Date lastEditTime;

    private Short itemType;

    private Boolean isDeleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public NonDrug withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public NonDrug withCode(String code) {
        this.setCode(code);
        return this;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getNonDrugName() {
        return nonDrugName;
    }

    public NonDrug withNonDrugName(String nonDrugName) {
        this.setNonDrugName(nonDrugName);
        return this;
    }

    public void setNonDrugName(String nonDrugName) {
        this.nonDrugName = nonDrugName;
    }

    public String getStandard() {
        return standard;
    }

    public NonDrug withStandard(String standard) {
        this.setStandard(standard);
        return this;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public NonDrug withUnitPrice(Double unitPrice) {
        this.setUnitPrice(unitPrice);
        return this;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Integer getCategoryPaymentId() {
        return categoryPaymentId;
    }

    public NonDrug withCategoryPaymentId(Integer categoryPaymentId) {
        this.setCategoryPaymentId(categoryPaymentId);
        return this;
    }

    public void setCategoryPaymentId(Integer categoryPaymentId) {
        this.categoryPaymentId = categoryPaymentId;
    }

    public Integer getDeptId() {
        return deptId;
    }

    public NonDrug withDeptId(Integer deptId) {
        this.setDeptId(deptId);
        return this;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public String getPinyinMnemonicCode() {
        return pinyinMnemonicCode;
    }

    public NonDrug withPinyinMnemonicCode(String pinyinMnemonicCode) {
        this.setPinyinMnemonicCode(pinyinMnemonicCode);
        return this;
    }

    public void setPinyinMnemonicCode(String pinyinMnemonicCode) {
        this.pinyinMnemonicCode = pinyinMnemonicCode;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public NonDrug withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastEditTime() {
        return lastEditTime;
    }

    public NonDrug withLastEditTime(Date lastEditTime) {
        this.setLastEditTime(lastEditTime);
        return this;
    }

    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public Short getItemType() {
        return itemType;
    }

    public NonDrug withItemType(Short itemType) {
        this.setItemType(itemType);
        return this;
    }

    public void setItemType(Short itemType) {
        this.itemType = itemType;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public NonDrug withIsDeleted(Boolean isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", nonDrugName=").append(nonDrugName);
        sb.append(", standard=").append(standard);
        sb.append(", unitPrice=").append(unitPrice);
        sb.append(", categoryPaymentId=").append(categoryPaymentId);
        sb.append(", deptId=").append(deptId);
        sb.append(", pinyinMnemonicCode=").append(pinyinMnemonicCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastEditTime=").append(lastEditTime);
        sb.append(", itemType=").append(itemType);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NonDrug other = (NonDrug) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getNonDrugName() == null ? other.getNonDrugName() == null : this.getNonDrugName().equals(other.getNonDrugName()))
            && (this.getStandard() == null ? other.getStandard() == null : this.getStandard().equals(other.getStandard()))
            && (this.getUnitPrice() == null ? other.getUnitPrice() == null : this.getUnitPrice().equals(other.getUnitPrice()))
            && (this.getCategoryPaymentId() == null ? other.getCategoryPaymentId() == null : this.getCategoryPaymentId().equals(other.getCategoryPaymentId()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getPinyinMnemonicCode() == null ? other.getPinyinMnemonicCode() == null : this.getPinyinMnemonicCode().equals(other.getPinyinMnemonicCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastEditTime() == null ? other.getLastEditTime() == null : this.getLastEditTime().equals(other.getLastEditTime()))
            && (this.getItemType() == null ? other.getItemType() == null : this.getItemType().equals(other.getItemType()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getNonDrugName() == null) ? 0 : getNonDrugName().hashCode());
        result = prime * result + ((getStandard() == null) ? 0 : getStandard().hashCode());
        result = prime * result + ((getUnitPrice() == null) ? 0 : getUnitPrice().hashCode());
        result = prime * result + ((getCategoryPaymentId() == null) ? 0 : getCategoryPaymentId().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getPinyinMnemonicCode() == null) ? 0 : getPinyinMnemonicCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastEditTime() == null) ? 0 : getLastEditTime().hashCode());
        result = prime * result + ((getItemType() == null) ? 0 : getItemType().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}