package com.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class PaymentDtl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer regId;

    private Integer invoiceNo;

    private Integer itemId;

    private Boolean itemType;

    private String itemName;

    private Double itemUnitPrice;

    private Integer quantity;

    private Integer deptId;

    private Date prescriptionGenerationTime;

    private Integer generatorId;

    private Date paymentOperationTime;

    private Integer operatorId;

    private String method;

    private Integer relatedRefundId;

    private Boolean isDeleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public PaymentDtl withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRegId() {
        return regId;
    }

    public PaymentDtl withRegId(Integer regId) {
        this.setRegId(regId);
        return this;
    }

    public void setRegId(Integer regId) {
        this.regId = regId;
    }

    public Integer getInvoiceNo() {
        return invoiceNo;
    }

    public PaymentDtl withInvoiceNo(Integer invoiceNo) {
        this.setInvoiceNo(invoiceNo);
        return this;
    }

    public void setInvoiceNo(Integer invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    public Integer getItemId() {
        return itemId;
    }

    public PaymentDtl withItemId(Integer itemId) {
        this.setItemId(itemId);
        return this;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public Boolean getItemType() {
        return itemType;
    }

    public PaymentDtl withItemType(Boolean itemType) {
        this.setItemType(itemType);
        return this;
    }

    public void setItemType(Boolean itemType) {
        this.itemType = itemType;
    }

    public String getItemName() {
        return itemName;
    }

    public PaymentDtl withItemName(String itemName) {
        this.setItemName(itemName);
        return this;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public Double getItemUnitPrice() {
        return itemUnitPrice;
    }

    public PaymentDtl withItemUnitPrice(Double itemUnitPrice) {
        this.setItemUnitPrice(itemUnitPrice);
        return this;
    }

    public void setItemUnitPrice(Double itemUnitPrice) {
        this.itemUnitPrice = itemUnitPrice;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public PaymentDtl withQuantity(Integer quantity) {
        this.setQuantity(quantity);
        return this;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getDeptId() {
        return deptId;
    }

    public PaymentDtl withDeptId(Integer deptId) {
        this.setDeptId(deptId);
        return this;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public Date getPrescriptionGenerationTime() {
        return prescriptionGenerationTime;
    }

    public PaymentDtl withPrescriptionGenerationTime(Date prescriptionGenerationTime) {
        this.setPrescriptionGenerationTime(prescriptionGenerationTime);
        return this;
    }

    public void setPrescriptionGenerationTime(Date prescriptionGenerationTime) {
        this.prescriptionGenerationTime = prescriptionGenerationTime;
    }

    public Integer getGeneratorId() {
        return generatorId;
    }

    public PaymentDtl withGeneratorId(Integer generatorId) {
        this.setGeneratorId(generatorId);
        return this;
    }

    public void setGeneratorId(Integer generatorId) {
        this.generatorId = generatorId;
    }

    public Date getPaymentOperationTime() {
        return paymentOperationTime;
    }

    public PaymentDtl withPaymentOperationTime(Date paymentOperationTime) {
        this.setPaymentOperationTime(paymentOperationTime);
        return this;
    }

    public void setPaymentOperationTime(Date paymentOperationTime) {
        this.paymentOperationTime = paymentOperationTime;
    }

    public Integer getOperatorId() {
        return operatorId;
    }

    public PaymentDtl withOperatorId(Integer operatorId) {
        this.setOperatorId(operatorId);
        return this;
    }

    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    public String getMethod() {
        return method;
    }

    public PaymentDtl withMethod(String method) {
        this.setMethod(method);
        return this;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public Integer getRelatedRefundId() {
        return relatedRefundId;
    }

    public PaymentDtl withRelatedRefundId(Integer relatedRefundId) {
        this.setRelatedRefundId(relatedRefundId);
        return this;
    }

    public void setRelatedRefundId(Integer relatedRefundId) {
        this.relatedRefundId = relatedRefundId;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public PaymentDtl withIsDeleted(Boolean isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", regId=").append(regId);
        sb.append(", invoiceNo=").append(invoiceNo);
        sb.append(", itemId=").append(itemId);
        sb.append(", itemType=").append(itemType);
        sb.append(", itemName=").append(itemName);
        sb.append(", itemUnitPrice=").append(itemUnitPrice);
        sb.append(", quantity=").append(quantity);
        sb.append(", deptId=").append(deptId);
        sb.append(", prescriptionGenerationTime=").append(prescriptionGenerationTime);
        sb.append(", generatorId=").append(generatorId);
        sb.append(", paymentOperationTime=").append(paymentOperationTime);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", method=").append(method);
        sb.append(", relatedRefundId=").append(relatedRefundId);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaymentDtl other = (PaymentDtl) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRegId() == null ? other.getRegId() == null : this.getRegId().equals(other.getRegId()))
            && (this.getInvoiceNo() == null ? other.getInvoiceNo() == null : this.getInvoiceNo().equals(other.getInvoiceNo()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getItemType() == null ? other.getItemType() == null : this.getItemType().equals(other.getItemType()))
            && (this.getItemName() == null ? other.getItemName() == null : this.getItemName().equals(other.getItemName()))
            && (this.getItemUnitPrice() == null ? other.getItemUnitPrice() == null : this.getItemUnitPrice().equals(other.getItemUnitPrice()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getPrescriptionGenerationTime() == null ? other.getPrescriptionGenerationTime() == null : this.getPrescriptionGenerationTime().equals(other.getPrescriptionGenerationTime()))
            && (this.getGeneratorId() == null ? other.getGeneratorId() == null : this.getGeneratorId().equals(other.getGeneratorId()))
            && (this.getPaymentOperationTime() == null ? other.getPaymentOperationTime() == null : this.getPaymentOperationTime().equals(other.getPaymentOperationTime()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getRelatedRefundId() == null ? other.getRelatedRefundId() == null : this.getRelatedRefundId().equals(other.getRelatedRefundId()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRegId() == null) ? 0 : getRegId().hashCode());
        result = prime * result + ((getInvoiceNo() == null) ? 0 : getInvoiceNo().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getItemType() == null) ? 0 : getItemType().hashCode());
        result = prime * result + ((getItemName() == null) ? 0 : getItemName().hashCode());
        result = prime * result + ((getItemUnitPrice() == null) ? 0 : getItemUnitPrice().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getPrescriptionGenerationTime() == null) ? 0 : getPrescriptionGenerationTime().hashCode());
        result = prime * result + ((getGeneratorId() == null) ? 0 : getGeneratorId().hashCode());
        result = prime * result + ((getPaymentOperationTime() == null) ? 0 : getPaymentOperationTime().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getRelatedRefundId() == null) ? 0 : getRelatedRefundId().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}