package com.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class Registration implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registration
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registration
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer caseNo;

    private String patientName;

    private Short sex;

    private String personalId;

    private Date birthday;

    private Integer age;

    private String ageType;

    private String address;

    private Date seeDate;

    private String noon;

    private Integer deptId;

    private Integer doctorId;

    private Integer regLevelId;

    private String settlementType;

    private Boolean needCaseBook;

    private Date regTime;

    private Integer operator;

    private Integer inspectionStatus;

    private Boolean isDeleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Registration withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCaseNo() {
        return caseNo;
    }

    public Registration withCaseNo(Integer caseNo) {
        this.setCaseNo(caseNo);
        return this;
    }

    public void setCaseNo(Integer caseNo) {
        this.caseNo = caseNo;
    }

    public String getPatientName() {
        return patientName;
    }

    public Registration withPatientName(String patientName) {
        this.setPatientName(patientName);
        return this;
    }

    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    public Short getSex() {
        return sex;
    }

    public Registration withSex(Short sex) {
        this.setSex(sex);
        return this;
    }

    public void setSex(Short sex) {
        this.sex = sex;
    }

    public String getPersonalId() {
        return personalId;
    }

    public Registration withPersonalId(String personalId) {
        this.setPersonalId(personalId);
        return this;
    }

    public void setPersonalId(String personalId) {
        this.personalId = personalId;
    }

    public Date getBirthday() {
        return birthday;
    }

    public Registration withBirthday(Date birthday) {
        this.setBirthday(birthday);
        return this;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Integer getAge() {
        return age;
    }

    public Registration withAge(Integer age) {
        this.setAge(age);
        return this;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getAgeType() {
        return ageType;
    }

    public Registration withAgeType(String ageType) {
        this.setAgeType(ageType);
        return this;
    }

    public void setAgeType(String ageType) {
        this.ageType = ageType;
    }

    public String getAddress() {
        return address;
    }

    public Registration withAddress(String address) {
        this.setAddress(address);
        return this;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getSeeDate() {
        return seeDate;
    }

    public Registration withSeeDate(Date seeDate) {
        this.setSeeDate(seeDate);
        return this;
    }

    public void setSeeDate(Date seeDate) {
        this.seeDate = seeDate;
    }

    public String getNoon() {
        return noon;
    }

    public Registration withNoon(String noon) {
        this.setNoon(noon);
        return this;
    }

    public void setNoon(String noon) {
        this.noon = noon;
    }

    public Integer getDeptId() {
        return deptId;
    }

    public Registration withDeptId(Integer deptId) {
        this.setDeptId(deptId);
        return this;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public Integer getDoctorId() {
        return doctorId;
    }

    public Registration withDoctorId(Integer doctorId) {
        this.setDoctorId(doctorId);
        return this;
    }

    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    public Integer getRegLevelId() {
        return regLevelId;
    }

    public Registration withRegLevelId(Integer regLevelId) {
        this.setRegLevelId(regLevelId);
        return this;
    }

    public void setRegLevelId(Integer regLevelId) {
        this.regLevelId = regLevelId;
    }

    public String getSettlementType() {
        return settlementType;
    }

    public Registration withSettlementType(String settlementType) {
        this.setSettlementType(settlementType);
        return this;
    }

    public void setSettlementType(String settlementType) {
        this.settlementType = settlementType;
    }

    public Boolean getNeedCaseBook() {
        return needCaseBook;
    }

    public Registration withNeedCaseBook(Boolean needCaseBook) {
        this.setNeedCaseBook(needCaseBook);
        return this;
    }

    public void setNeedCaseBook(Boolean needCaseBook) {
        this.needCaseBook = needCaseBook;
    }

    public Date getRegTime() {
        return regTime;
    }

    public Registration withRegTime(Date regTime) {
        this.setRegTime(regTime);
        return this;
    }

    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    public Integer getOperator() {
        return operator;
    }

    public Registration withOperator(Integer operator) {
        this.setOperator(operator);
        return this;
    }

    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    public Integer getInspectionStatus() {
        return inspectionStatus;
    }

    public Registration withInspectionStatus(Integer inspectionStatus) {
        this.setInspectionStatus(inspectionStatus);
        return this;
    }

    public void setInspectionStatus(Integer inspectionStatus) {
        this.inspectionStatus = inspectionStatus;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public Registration withIsDeleted(Boolean isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", caseNo=").append(caseNo);
        sb.append(", patientName=").append(patientName);
        sb.append(", sex=").append(sex);
        sb.append(", personalId=").append(personalId);
        sb.append(", birthday=").append(birthday);
        sb.append(", age=").append(age);
        sb.append(", ageType=").append(ageType);
        sb.append(", address=").append(address);
        sb.append(", seeDate=").append(seeDate);
        sb.append(", noon=").append(noon);
        sb.append(", deptId=").append(deptId);
        sb.append(", doctorId=").append(doctorId);
        sb.append(", regLevelId=").append(regLevelId);
        sb.append(", settlementType=").append(settlementType);
        sb.append(", needCaseBook=").append(needCaseBook);
        sb.append(", regTime=").append(regTime);
        sb.append(", operator=").append(operator);
        sb.append(", inspectionStatus=").append(inspectionStatus);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Registration other = (Registration) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCaseNo() == null ? other.getCaseNo() == null : this.getCaseNo().equals(other.getCaseNo()))
            && (this.getPatientName() == null ? other.getPatientName() == null : this.getPatientName().equals(other.getPatientName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getPersonalId() == null ? other.getPersonalId() == null : this.getPersonalId().equals(other.getPersonalId()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getAgeType() == null ? other.getAgeType() == null : this.getAgeType().equals(other.getAgeType()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getSeeDate() == null ? other.getSeeDate() == null : this.getSeeDate().equals(other.getSeeDate()))
            && (this.getNoon() == null ? other.getNoon() == null : this.getNoon().equals(other.getNoon()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getDoctorId() == null ? other.getDoctorId() == null : this.getDoctorId().equals(other.getDoctorId()))
            && (this.getRegLevelId() == null ? other.getRegLevelId() == null : this.getRegLevelId().equals(other.getRegLevelId()))
            && (this.getSettlementType() == null ? other.getSettlementType() == null : this.getSettlementType().equals(other.getSettlementType()))
            && (this.getNeedCaseBook() == null ? other.getNeedCaseBook() == null : this.getNeedCaseBook().equals(other.getNeedCaseBook()))
            && (this.getRegTime() == null ? other.getRegTime() == null : this.getRegTime().equals(other.getRegTime()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getInspectionStatus() == null ? other.getInspectionStatus() == null : this.getInspectionStatus().equals(other.getInspectionStatus()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCaseNo() == null) ? 0 : getCaseNo().hashCode());
        result = prime * result + ((getPatientName() == null) ? 0 : getPatientName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getPersonalId() == null) ? 0 : getPersonalId().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getAgeType() == null) ? 0 : getAgeType().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getSeeDate() == null) ? 0 : getSeeDate().hashCode());
        result = prime * result + ((getNoon() == null) ? 0 : getNoon().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getDoctorId() == null) ? 0 : getDoctorId().hashCode());
        result = prime * result + ((getRegLevelId() == null) ? 0 : getRegLevelId().hashCode());
        result = prime * result + ((getSettlementType() == null) ? 0 : getSettlementType().hashCode());
        result = prime * result + ((getNeedCaseBook() == null) ? 0 : getNeedCaseBook().hashCode());
        result = prime * result + ((getRegTime() == null) ? 0 : getRegTime().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getInspectionStatus() == null) ? 0 : getInspectionStatus().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}