package com.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class Schedule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Date arrangeTime;

    private Integer deptId;

    private Integer doctorId;

    private String noon;

    private Integer scheduleRuleId;

    private Boolean isDeleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Schedule withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getArrangeTime() {
        return arrangeTime;
    }

    public Schedule withArrangeTime(Date arrangeTime) {
        this.setArrangeTime(arrangeTime);
        return this;
    }

    public void setArrangeTime(Date arrangeTime) {
        this.arrangeTime = arrangeTime;
    }

    public Integer getDeptId() {
        return deptId;
    }

    public Schedule withDeptId(Integer deptId) {
        this.setDeptId(deptId);
        return this;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public Integer getDoctorId() {
        return doctorId;
    }

    public Schedule withDoctorId(Integer doctorId) {
        this.setDoctorId(doctorId);
        return this;
    }

    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    public String getNoon() {
        return noon;
    }

    public Schedule withNoon(String noon) {
        this.setNoon(noon);
        return this;
    }

    public void setNoon(String noon) {
        this.noon = noon;
    }

    public Integer getScheduleRuleId() {
        return scheduleRuleId;
    }

    public Schedule withScheduleRuleId(Integer scheduleRuleId) {
        this.setScheduleRuleId(scheduleRuleId);
        return this;
    }

    public void setScheduleRuleId(Integer scheduleRuleId) {
        this.scheduleRuleId = scheduleRuleId;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public Schedule withIsDeleted(Boolean isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", arrangeTime=").append(arrangeTime);
        sb.append(", deptId=").append(deptId);
        sb.append(", doctorId=").append(doctorId);
        sb.append(", noon=").append(noon);
        sb.append(", scheduleRuleId=").append(scheduleRuleId);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Schedule other = (Schedule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getArrangeTime() == null ? other.getArrangeTime() == null : this.getArrangeTime().equals(other.getArrangeTime()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getDoctorId() == null ? other.getDoctorId() == null : this.getDoctorId().equals(other.getDoctorId()))
            && (this.getNoon() == null ? other.getNoon() == null : this.getNoon().equals(other.getNoon()))
            && (this.getScheduleRuleId() == null ? other.getScheduleRuleId() == null : this.getScheduleRuleId().equals(other.getScheduleRuleId()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getArrangeTime() == null) ? 0 : getArrangeTime().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getDoctorId() == null) ? 0 : getDoctorId().hashCode());
        result = prime * result + ((getNoon() == null) ? 0 : getNoon().hashCode());
        result = prime * result + ((getScheduleRuleId() == null) ? 0 : getScheduleRuleId().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}