package com.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class TemplateHerb implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String name;

    private Integer doctorId;

    private Date createTime;

    private String prescriptionType;

    private Integer number;

    private String method;

    private String treatment;

    private String treatmentDetail;

    private String doctorAdvice;

    private String range;

    private Boolean isDeleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public TemplateHerb withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public TemplateHerb withName(String name) {
        this.setName(name);
        return this;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getDoctorId() {
        return doctorId;
    }

    public TemplateHerb withDoctorId(Integer doctorId) {
        this.setDoctorId(doctorId);
        return this;
    }

    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public TemplateHerb withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getPrescriptionType() {
        return prescriptionType;
    }

    public TemplateHerb withPrescriptionType(String prescriptionType) {
        this.setPrescriptionType(prescriptionType);
        return this;
    }

    public void setPrescriptionType(String prescriptionType) {
        this.prescriptionType = prescriptionType;
    }

    public Integer getNumber() {
        return number;
    }

    public TemplateHerb withNumber(Integer number) {
        this.setNumber(number);
        return this;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getMethod() {
        return method;
    }

    public TemplateHerb withMethod(String method) {
        this.setMethod(method);
        return this;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getTreatment() {
        return treatment;
    }

    public TemplateHerb withTreatment(String treatment) {
        this.setTreatment(treatment);
        return this;
    }

    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    public String getTreatmentDetail() {
        return treatmentDetail;
    }

    public TemplateHerb withTreatmentDetail(String treatmentDetail) {
        this.setTreatmentDetail(treatmentDetail);
        return this;
    }

    public void setTreatmentDetail(String treatmentDetail) {
        this.treatmentDetail = treatmentDetail;
    }

    public String getDoctorAdvice() {
        return doctorAdvice;
    }

    public TemplateHerb withDoctorAdvice(String doctorAdvice) {
        this.setDoctorAdvice(doctorAdvice);
        return this;
    }

    public void setDoctorAdvice(String doctorAdvice) {
        this.doctorAdvice = doctorAdvice;
    }

    public String getRange() {
        return range;
    }

    public TemplateHerb withRange(String range) {
        this.setRange(range);
        return this;
    }

    public void setRange(String range) {
        this.range = range;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public TemplateHerb withIsDeleted(Boolean isDeleted) {
        this.setIsDeleted(isDeleted);
        return this;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", doctorId=").append(doctorId);
        sb.append(", createTime=").append(createTime);
        sb.append(", prescriptionType=").append(prescriptionType);
        sb.append(", number=").append(number);
        sb.append(", method=").append(method);
        sb.append(", treatment=").append(treatment);
        sb.append(", treatmentDetail=").append(treatmentDetail);
        sb.append(", doctorAdvice=").append(doctorAdvice);
        sb.append(", range=").append(range);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TemplateHerb other = (TemplateHerb) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDoctorId() == null ? other.getDoctorId() == null : this.getDoctorId().equals(other.getDoctorId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getPrescriptionType() == null ? other.getPrescriptionType() == null : this.getPrescriptionType().equals(other.getPrescriptionType()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getTreatment() == null ? other.getTreatment() == null : this.getTreatment().equals(other.getTreatment()))
            && (this.getTreatmentDetail() == null ? other.getTreatmentDetail() == null : this.getTreatmentDetail().equals(other.getTreatmentDetail()))
            && (this.getDoctorAdvice() == null ? other.getDoctorAdvice() == null : this.getDoctorAdvice().equals(other.getDoctorAdvice()))
            && (this.getRange() == null ? other.getRange() == null : this.getRange().equals(other.getRange()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDoctorId() == null) ? 0 : getDoctorId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getPrescriptionType() == null) ? 0 : getPrescriptionType().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getTreatment() == null) ? 0 : getTreatment().hashCode());
        result = prime * result + ((getTreatmentDetail() == null) ? 0 : getTreatmentDetail().hashCode());
        result = prime * result + ((getDoctorAdvice() == null) ? 0 : getDoctorAdvice().hashCode());
        result = prime * result + ((getRange() == null) ? 0 : getRange().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}