package com.neu.his.Dao;

import com.neu.his.entity.CategoryPayment;
import com.neu.his.entity.CategoryPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CategoryPaymentMapper {
    @SelectProvider(type=CategoryPaymentSqlProvider.class, method="countByExample")
    long countByExample(CategoryPaymentExample example);

    @DeleteProvider(type=CategoryPaymentSqlProvider.class, method="deleteByExample")
    int deleteByExample(CategoryPaymentExample example);

    @Delete({
        "delete from category_payment",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into category_payment (code, category_name, ",
        "is_deleted)",
        "values (#{code,jdbcType=VARCHAR}, #{categoryName,jdbcType=VARCHAR}, ",
        "#{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CategoryPayment record);

    @InsertProvider(type=CategoryPaymentSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CategoryPayment record);

    @SelectProvider(type=CategoryPaymentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<CategoryPayment> selectByExample(CategoryPaymentExample example);

    @Select({
        "select",
        "id, code, category_name, is_deleted",
        "from category_payment",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    CategoryPayment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_payment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategoryPayment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=CategoryPaymentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CategoryPayment record, @Param("example") CategoryPaymentExample example);

    @UpdateProvider(type=CategoryPaymentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CategoryPayment record, @Param("example") CategoryPaymentExample example);

    @UpdateProvider(type=CategoryPaymentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CategoryPayment record);

    @Update({
        "update category_payment",
        "set code = #{code,jdbcType=VARCHAR},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CategoryPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_payment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategoryPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_payment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}