package com.neu.his.Dao;

import com.neu.his.entity.CategoryDisease;
import com.neu.his.entity.CategoryDiseaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CategoryDiseaseMapper {
    @SelectProvider(type=CategoryDiseaseSqlProvider.class, method="countByExample")
    long countByExample(CategoryDiseaseExample example);

    @DeleteProvider(type=CategoryDiseaseSqlProvider.class, method="deleteByExample")
    int deleteByExample(CategoryDiseaseExample example);

    @Delete({
        "delete from category_disease",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into category_disease (code, category_name, ",
        "sequence, disease_flag, ",
        "is_deleted)",
        "values (#{code,jdbcType=VARCHAR}, #{categoryName,jdbcType=VARCHAR}, ",
        "#{sequence,jdbcType=VARCHAR}, #{diseaseFlag,jdbcType=INTEGER}, ",
        "#{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CategoryDisease record);

    @InsertProvider(type=CategoryDiseaseSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CategoryDisease record);

    @SelectProvider(type=CategoryDiseaseSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.VARCHAR),
        @Result(column="disease_flag", property="diseaseFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<CategoryDisease> selectByExample(CategoryDiseaseExample example);

    @Select({
        "select",
        "id, code, category_name, sequence, disease_flag, is_deleted",
        "from category_disease",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.VARCHAR),
        @Result(column="disease_flag", property="diseaseFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    CategoryDisease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategoryDisease selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=CategoryDiseaseSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CategoryDisease record, @Param("example") CategoryDiseaseExample example);

    @UpdateProvider(type=CategoryDiseaseSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CategoryDisease record, @Param("example") CategoryDiseaseExample example);

    @UpdateProvider(type=CategoryDiseaseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CategoryDisease record);

    @Update({
        "update category_disease",
        "set code = #{code,jdbcType=VARCHAR},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "sequence = #{sequence,jdbcType=VARCHAR},",
          "disease_flag = #{diseaseFlag,jdbcType=INTEGER},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CategoryDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategoryDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}