package com.neu.his.Dao;

import com.neu.his.entity.CategoryConstant;
import com.neu.his.entity.CategoryConstantExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CategoryConstantMapper {
    @SelectProvider(type=CategoryConstantSqlProvider.class, method="countByExample")
    long countByExample(CategoryConstantExample example);

    @DeleteProvider(type=CategoryConstantSqlProvider.class, method="deleteByExample")
    int deleteByExample(CategoryConstantExample example);

    @Delete({
        "delete from category_constant",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into category_constant (code, category_name, ",
        "is_deleted)",
        "values (#{code,jdbcType=VARCHAR}, #{categoryName,jdbcType=VARCHAR}, ",
        "#{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CategoryConstant record);

    @InsertProvider(type=CategoryConstantSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CategoryConstant record);

    @SelectProvider(type=CategoryConstantSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<CategoryConstant> selectByExample(CategoryConstantExample example);

    @Select({
        "select",
        "id, code, category_name, is_deleted",
        "from category_constant",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    CategoryConstant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategoryConstant selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=CategoryConstantSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CategoryConstant record, @Param("example") CategoryConstantExample example);

    @UpdateProvider(type=CategoryConstantSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CategoryConstant record, @Param("example") CategoryConstantExample example);

    @UpdateProvider(type=CategoryConstantSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CategoryConstant record);

    @Update({
        "update category_constant",
        "set code = #{code,jdbcType=VARCHAR},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CategoryConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategoryConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}