package com.neu.his.Dao;

import com.neu.his.entity.CategorySettlement;
import com.neu.his.entity.CategorySettlementExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CategorySettlementMapper {
    @SelectProvider(type=CategorySettlementSqlProvider.class, method="countByExample")
    long countByExample(CategorySettlementExample example);

    @DeleteProvider(type=CategorySettlementSqlProvider.class, method="deleteByExample")
    int deleteByExample(CategorySettlementExample example);

    @Delete({
        "delete from category_settlement",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into category_settlement (category_no, category_name, ",
        "sequence, is_deleted)",
        "values (#{categoryNo,jdbcType=VARCHAR}, #{categoryName,jdbcType=VARCHAR}, ",
        "#{sequence,jdbcType=VARCHAR}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CategorySettlement record);

    @InsertProvider(type=CategorySettlementSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CategorySettlement record);

    @SelectProvider(type=CategorySettlementSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_no", property="categoryNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<CategorySettlement> selectByExample(CategorySettlementExample example);

    @Select({
        "select",
        "id, category_no, category_name, sequence, is_deleted",
        "from category_settlement",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_no", property="categoryNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_name", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    CategorySettlement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategorySettlement selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=CategorySettlementSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CategorySettlement record, @Param("example") CategorySettlementExample example);

    @UpdateProvider(type=CategorySettlementSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CategorySettlement record, @Param("example") CategorySettlementExample example);

    @UpdateProvider(type=CategorySettlementSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CategorySettlement record);

    @Update({
        "update category_settlement",
        "set category_no = #{categoryNo,jdbcType=VARCHAR},",
          "category_name = #{categoryName,jdbcType=VARCHAR},",
          "sequence = #{sequence,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CategorySettlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategorySettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}