package com.neu.his.Dao;

import com.neu.his.entity.Constant;
import com.neu.his.entity.ConstantExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ConstantMapper {
    @SelectProvider(type=ConstantSqlProvider.class, method="countByExample")
    long countByExample(ConstantExample example);

    @DeleteProvider(type=ConstantSqlProvider.class, method="deleteByExample")
    int deleteByExample(ConstantExample example);

    @Delete({
        "delete from constant",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into constant (category_id, code, ",
        "constant_name, is_deleted)",
        "values (#{categoryId,jdbcType=INTEGER}, #{code,jdbcType=VARCHAR}, ",
        "#{constantName,jdbcType=VARCHAR}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Constant record);

    @InsertProvider(type=ConstantSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Constant record);

    @SelectProvider(type=ConstantSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="constant_name", property="constantName", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<Constant> selectByExample(ConstantExample example);

    @Select({
        "select",
        "id, category_id, code, constant_name, is_deleted",
        "from constant",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="constant_name", property="constantName", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    Constant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Constant selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=ConstantSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Constant record, @Param("example") ConstantExample example);

    @UpdateProvider(type=ConstantSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Constant record, @Param("example") ConstantExample example);

    @UpdateProvider(type=ConstantSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Constant record);

    @Update({
        "update constant",
        "set category_id = #{categoryId,jdbcType=INTEGER},",
          "code = #{code,jdbcType=VARCHAR},",
          "constant_name = #{constantName,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}