package com.neu.his.Dao;

import com.neu.his.entity.Diagnosis;
import com.neu.his.entity.DiagnosisExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface DiagnosisMapper {
    @SelectProvider(type=DiagnosisSqlProvider.class, method="countByExample")
    long countByExample(DiagnosisExample example);

    @DeleteProvider(type=DiagnosisSqlProvider.class, method="deleteByExample")
    int deleteByExample(DiagnosisExample example);

    @Delete({
        "delete from diagnosis",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into diagnosis (case_id, reg_id, ",
        "disease_id, diagnosis_type, ",
        "onset_time, diagnosis_class, ",
        "is_deleted)",
        "values (#{caseId,jdbcType=INTEGER}, #{regId,jdbcType=INTEGER}, ",
        "#{diseaseId,jdbcType=INTEGER}, #{diagnosisType,jdbcType=BIT}, ",
        "#{onsetTime,jdbcType=TIMESTAMP}, #{diagnosisClass,jdbcType=BIT}, ",
        "#{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Diagnosis record);

    @InsertProvider(type=DiagnosisSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Diagnosis record);

    @SelectProvider(type=DiagnosisSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="case_id", property="caseId", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_id", property="regId", jdbcType=JdbcType.INTEGER),
        @Result(column="disease_id", property="diseaseId", jdbcType=JdbcType.INTEGER),
        @Result(column="diagnosis_type", property="diagnosisType", jdbcType=JdbcType.BIT),
        @Result(column="onset_time", property="onsetTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="diagnosis_class", property="diagnosisClass", jdbcType=JdbcType.BIT),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<Diagnosis> selectByExample(DiagnosisExample example);

    @Select({
        "select",
        "id, case_id, reg_id, disease_id, diagnosis_type, onset_time, diagnosis_class, ",
        "is_deleted",
        "from diagnosis",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="case_id", property="caseId", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_id", property="regId", jdbcType=JdbcType.INTEGER),
        @Result(column="disease_id", property="diseaseId", jdbcType=JdbcType.INTEGER),
        @Result(column="diagnosis_type", property="diagnosisType", jdbcType=JdbcType.BIT),
        @Result(column="onset_time", property="onsetTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="diagnosis_class", property="diagnosisClass", jdbcType=JdbcType.BIT),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    Diagnosis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Diagnosis selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=DiagnosisSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Diagnosis record, @Param("example") DiagnosisExample example);

    @UpdateProvider(type=DiagnosisSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Diagnosis record, @Param("example") DiagnosisExample example);

    @UpdateProvider(type=DiagnosisSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Diagnosis record);

    @Update({
        "update diagnosis",
        "set case_id = #{caseId,jdbcType=INTEGER},",
          "reg_id = #{regId,jdbcType=INTEGER},",
          "disease_id = #{diseaseId,jdbcType=INTEGER},",
          "diagnosis_type = #{diagnosisType,jdbcType=BIT},",
          "onset_time = #{onsetTime,jdbcType=TIMESTAMP},",
          "diagnosis_class = #{diagnosisClass,jdbcType=BIT},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Diagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DiagnosisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}