package com.neu.his.Dao;

import com.neu.his.entity.Disease;
import com.neu.his.entity.DiseaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface DiseaseMapper {
    @SelectProvider(type=DiseaseSqlProvider.class, method="countByExample")
    long countByExample(DiseaseExample example);

    @DeleteProvider(type=DiseaseSqlProvider.class, method="deleteByExample")
    int deleteByExample(DiseaseExample example);

    @Delete({
        "delete from disease",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into disease (code, desease_name, ",
        "ICD, category_id, ",
        "is_deleted)",
        "values (#{code,jdbcType=VARCHAR}, #{deseaseName,jdbcType=VARCHAR}, ",
        "#{icd,jdbcType=VARCHAR}, #{categoryId,jdbcType=INTEGER}, ",
        "#{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Disease record);

    @InsertProvider(type=DiseaseSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Disease record);

    @SelectProvider(type=DiseaseSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="desease_name", property="deseaseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICD", property="icd", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<Disease> selectByExample(DiseaseExample example);

    @Select({
        "select",
        "id, code, desease_name, ICD, category_id, is_deleted",
        "from disease",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="desease_name", property="deseaseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICD", property="icd", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    Disease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Disease selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=DiseaseSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Disease record, @Param("example") DiseaseExample example);

    @UpdateProvider(type=DiseaseSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Disease record, @Param("example") DiseaseExample example);

    @UpdateProvider(type=DiseaseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Disease record);

    @Update({
        "update disease",
        "set code = #{code,jdbcType=VARCHAR},",
          "desease_name = #{deseaseName,jdbcType=VARCHAR},",
          "ICD = #{icd,jdbcType=VARCHAR},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}