package com.neu.his.Dao;

import com.neu.his.entity.Invoice;
import com.neu.his.entity.InvoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface InvoiceMapper {
    @SelectProvider(type=InvoiceSqlProvider.class, method="countByExample")
    long countByExample(InvoiceExample example);

    @DeleteProvider(type=InvoiceSqlProvider.class, method="deleteByExample")
    int deleteByExample(InvoiceExample example);

    @Delete({
        "delete from invoice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into invoice (invoice_no, amount, ",
        "type, operate_time, ",
        "operator_id, reg_id, ",
        "pay_method, red_invoice_no, ",
        "invoice_status, is_deleted)",
        "values (#{invoiceNo,jdbcType=INTEGER}, #{amount,jdbcType=DOUBLE}, ",
        "#{type,jdbcType=INTEGER}, #{operateTime,jdbcType=TIMESTAMP}, ",
        "#{operatorId,jdbcType=INTEGER}, #{regId,jdbcType=INTEGER}, ",
        "#{payMethod,jdbcType=INTEGER}, #{redInvoiceNo,jdbcType=INTEGER}, ",
        "#{invoiceStatus,jdbcType=INTEGER}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Invoice record);

    @InsertProvider(type=InvoiceSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Invoice record);

    @SelectProvider(type=InvoiceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="invoice_no", property="invoiceNo", jdbcType=JdbcType.INTEGER),
        @Result(column="amount", property="amount", jdbcType=JdbcType.DOUBLE),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_time", property="operateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_id", property="regId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_method", property="payMethod", jdbcType=JdbcType.INTEGER),
        @Result(column="red_invoice_no", property="redInvoiceNo", jdbcType=JdbcType.INTEGER),
        @Result(column="invoice_status", property="invoiceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<Invoice> selectByExample(InvoiceExample example);

    @Select({
        "select",
        "id, invoice_no, amount, type, operate_time, operator_id, reg_id, pay_method, ",
        "red_invoice_no, invoice_status, is_deleted",
        "from invoice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="invoice_no", property="invoiceNo", jdbcType=JdbcType.INTEGER),
        @Result(column="amount", property="amount", jdbcType=JdbcType.DOUBLE),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_time", property="operateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_id", property="regId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_method", property="payMethod", jdbcType=JdbcType.INTEGER),
        @Result(column="red_invoice_no", property="redInvoiceNo", jdbcType=JdbcType.INTEGER),
        @Result(column="invoice_status", property="invoiceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    Invoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Invoice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=InvoiceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    @UpdateProvider(type=InvoiceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    @UpdateProvider(type=InvoiceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Invoice record);

    @Update({
        "update invoice",
        "set invoice_no = #{invoiceNo,jdbcType=INTEGER},",
          "amount = #{amount,jdbcType=DOUBLE},",
          "type = #{type,jdbcType=INTEGER},",
          "operate_time = #{operateTime,jdbcType=TIMESTAMP},",
          "operator_id = #{operatorId,jdbcType=INTEGER},",
          "reg_id = #{regId,jdbcType=INTEGER},",
          "pay_method = #{payMethod,jdbcType=INTEGER},",
          "red_invoice_no = #{redInvoiceNo,jdbcType=INTEGER},",
          "invoice_status = #{invoiceStatus,jdbcType=INTEGER},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}