package com.neu.his.Dao;

import com.neu.his.entity.OperatorSettlement;
import com.neu.his.entity.OperatorSettlementExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface OperatorSettlementMapper {
    @SelectProvider(type=OperatorSettlementSqlProvider.class, method="countByExample")
    long countByExample(OperatorSettlementExample example);

    @DeleteProvider(type=OperatorSettlementSqlProvider.class, method="deleteByExample")
    int deleteByExample(OperatorSettlementExample example);

    @Delete({
        "delete from operator_settlement",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into operator_settlement (operator_id, start_time, ",
        "end_time, is_deleted)",
        "values (#{operatorId,jdbcType=INTEGER}, #{startTime,jdbcType=DATE}, ",
        "#{endTime,jdbcType=DATE}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(OperatorSettlement record);

    @InsertProvider(type=OperatorSettlementSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(OperatorSettlement record);

    @SelectProvider(type=OperatorSettlementSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.INTEGER),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.DATE),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.DATE),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<OperatorSettlement> selectByExample(OperatorSettlementExample example);

    @Select({
        "select",
        "id, operator_id, start_time, end_time, is_deleted",
        "from operator_settlement",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.INTEGER),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.DATE),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.DATE),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    OperatorSettlement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OperatorSettlement selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=OperatorSettlementSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OperatorSettlement record, @Param("example") OperatorSettlementExample example);

    @UpdateProvider(type=OperatorSettlementSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OperatorSettlement record, @Param("example") OperatorSettlementExample example);

    @UpdateProvider(type=OperatorSettlementSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OperatorSettlement record);

    @Update({
        "update operator_settlement",
        "set operator_id = #{operatorId,jdbcType=INTEGER},",
          "start_time = #{startTime,jdbcType=DATE},",
          "end_time = #{endTime,jdbcType=DATE},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OperatorSettlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") OperatorSettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}