package com.neu.his.Dao;

import com.neu.his.entity.PrescriptionHerbDtl;
import com.neu.his.entity.PrescriptionHerbDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface PrescriptionHerbDtlMapper {
    @SelectProvider(type=PrescriptionHerbDtlSqlProvider.class, method="countByExample")
    long countByExample(PrescriptionHerbDtlExample example);

    @DeleteProvider(type=PrescriptionHerbDtlSqlProvider.class, method="deleteByExample")
    int deleteByExample(PrescriptionHerbDtlExample example);

    @Delete({
        "delete from prescription_herb_dtl",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into prescription_herb_dtl (prescription_id, herb_id, ",
        "consumption, unit_price, ",
        "description, is_deleted)",
        "values (#{prescriptionId,jdbcType=INTEGER}, #{herbId,jdbcType=INTEGER}, ",
        "#{consumption,jdbcType=VARCHAR}, #{unitPrice,jdbcType=DOUBLE}, ",
        "#{description,jdbcType=VARCHAR}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(PrescriptionHerbDtl record);

    @InsertProvider(type=PrescriptionHerbDtlSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(PrescriptionHerbDtl record);

    @SelectProvider(type=PrescriptionHerbDtlSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="prescription_id", property="prescriptionId", jdbcType=JdbcType.INTEGER),
        @Result(column="herb_id", property="herbId", jdbcType=JdbcType.INTEGER),
        @Result(column="consumption", property="consumption", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<PrescriptionHerbDtl> selectByExample(PrescriptionHerbDtlExample example);

    @Select({
        "select",
        "id, prescription_id, herb_id, consumption, unit_price, description, is_deleted",
        "from prescription_herb_dtl",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="prescription_id", property="prescriptionId", jdbcType=JdbcType.INTEGER),
        @Result(column="herb_id", property="herbId", jdbcType=JdbcType.INTEGER),
        @Result(column="consumption", property="consumption", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    PrescriptionHerbDtl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PrescriptionHerbDtl selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=PrescriptionHerbDtlSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PrescriptionHerbDtl record, @Param("example") PrescriptionHerbDtlExample example);

    @UpdateProvider(type=PrescriptionHerbDtlSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PrescriptionHerbDtl record, @Param("example") PrescriptionHerbDtlExample example);

    @UpdateProvider(type=PrescriptionHerbDtlSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PrescriptionHerbDtl record);

    @Update({
        "update prescription_herb_dtl",
        "set prescription_id = #{prescriptionId,jdbcType=INTEGER},",
          "herb_id = #{herbId,jdbcType=INTEGER},",
          "consumption = #{consumption,jdbcType=VARCHAR},",
          "unit_price = #{unitPrice,jdbcType=DOUBLE},",
          "description = #{description,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PrescriptionHerbDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PrescriptionHerbDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}