package com.neu.his.Dao;

import com.neu.his.entity.PrescriptionMedicine;
import com.neu.his.entity.PrescriptionMedicineExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface PrescriptionMedicineMapper {
    @SelectProvider(type=PrescriptionMedicineSqlProvider.class, method="countByExample")
    long countByExample(PrescriptionMedicineExample example);

    @DeleteProvider(type=PrescriptionMedicineSqlProvider.class, method="deleteByExample")
    int deleteByExample(PrescriptionMedicineExample example);

    @Delete({
        "delete from prescription_medicine",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into prescription_medicine (case_id, reg_id, ",
        "doctor_id, prescription_name, ",
        "generate_time, prescription_status, ",
        "is_deleted)",
        "values (#{caseId,jdbcType=INTEGER}, #{regId,jdbcType=INTEGER}, ",
        "#{doctorId,jdbcType=INTEGER}, #{prescriptionName,jdbcType=VARCHAR}, ",
        "#{generateTime,jdbcType=DATE}, #{prescriptionStatus,jdbcType=VARCHAR}, ",
        "#{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(PrescriptionMedicine record);

    @InsertProvider(type=PrescriptionMedicineSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(PrescriptionMedicine record);

    @SelectProvider(type=PrescriptionMedicineSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="case_id", property="caseId", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_id", property="regId", jdbcType=JdbcType.INTEGER),
        @Result(column="doctor_id", property="doctorId", jdbcType=JdbcType.INTEGER),
        @Result(column="prescription_name", property="prescriptionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="generate_time", property="generateTime", jdbcType=JdbcType.DATE),
        @Result(column="prescription_status", property="prescriptionStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<PrescriptionMedicine> selectByExample(PrescriptionMedicineExample example);

    @Select({
        "select",
        "id, case_id, reg_id, doctor_id, prescription_name, generate_time, prescription_status, ",
        "is_deleted",
        "from prescription_medicine",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="case_id", property="caseId", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_id", property="regId", jdbcType=JdbcType.INTEGER),
        @Result(column="doctor_id", property="doctorId", jdbcType=JdbcType.INTEGER),
        @Result(column="prescription_name", property="prescriptionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="generate_time", property="generateTime", jdbcType=JdbcType.DATE),
        @Result(column="prescription_status", property="prescriptionStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    PrescriptionMedicine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PrescriptionMedicine selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=PrescriptionMedicineSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PrescriptionMedicine record, @Param("example") PrescriptionMedicineExample example);

    @UpdateProvider(type=PrescriptionMedicineSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PrescriptionMedicine record, @Param("example") PrescriptionMedicineExample example);

    @UpdateProvider(type=PrescriptionMedicineSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PrescriptionMedicine record);

    @Update({
        "update prescription_medicine",
        "set case_id = #{caseId,jdbcType=INTEGER},",
          "reg_id = #{regId,jdbcType=INTEGER},",
          "doctor_id = #{doctorId,jdbcType=INTEGER},",
          "prescription_name = #{prescriptionName,jdbcType=VARCHAR},",
          "generate_time = #{generateTime,jdbcType=DATE},",
          "prescription_status = #{prescriptionStatus,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PrescriptionMedicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PrescriptionMedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}