package com.neu.his.Dao;

import com.neu.his.entity.ScheduleRule;
import com.neu.his.entity.ScheduleRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ScheduleRuleMapper {
    @SelectProvider(type=ScheduleRuleSqlProvider.class, method="countByExample")
    long countByExample(ScheduleRuleExample example);

    @DeleteProvider(type=ScheduleRuleSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScheduleRuleExample example);

    @Delete({
        "delete from schedule_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into schedule_rule (rule_name, dept_id, ",
        "doctor_id, days, ",
        "is_deleted)",
        "values (#{ruleName,jdbcType=VARCHAR}, #{deptId,jdbcType=INTEGER}, ",
        "#{doctorId,jdbcType=INTEGER}, #{days,jdbcType=VARCHAR}, ",
        "#{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ScheduleRule record);

    @InsertProvider(type=ScheduleRuleSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ScheduleRule record);

    @SelectProvider(type=ScheduleRuleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="rule_name", property="ruleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_id", property="deptId", jdbcType=JdbcType.INTEGER),
        @Result(column="doctor_id", property="doctorId", jdbcType=JdbcType.INTEGER),
        @Result(column="days", property="days", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<ScheduleRule> selectByExample(ScheduleRuleExample example);

    @Select({
        "select",
        "id, rule_name, dept_id, doctor_id, days, is_deleted",
        "from schedule_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="rule_name", property="ruleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dept_id", property="deptId", jdbcType=JdbcType.INTEGER),
        @Result(column="doctor_id", property="doctorId", jdbcType=JdbcType.INTEGER),
        @Result(column="days", property="days", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    ScheduleRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ScheduleRule selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=ScheduleRuleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScheduleRule record, @Param("example") ScheduleRuleExample example);

    @UpdateProvider(type=ScheduleRuleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScheduleRule record, @Param("example") ScheduleRuleExample example);

    @UpdateProvider(type=ScheduleRuleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScheduleRule record);

    @Update({
        "update schedule_rule",
        "set rule_name = #{ruleName,jdbcType=VARCHAR},",
          "dept_id = #{deptId,jdbcType=INTEGER},",
          "doctor_id = #{doctorId,jdbcType=INTEGER},",
          "days = #{days,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ScheduleRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ScheduleRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}