package com.neu.his.Dao;

import com.neu.his.entity.TemplateDtlMedi;
import com.neu.his.entity.TemplateDtlMediExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TemplateDtlMediMapper {
    @SelectProvider(type=TemplateDtlMediSqlProvider.class, method="countByExample")
    long countByExample(TemplateDtlMediExample example);

    @DeleteProvider(type=TemplateDtlMediSqlProvider.class, method="deleteByExample")
    int deleteByExample(TemplateDtlMediExample example);

    @Delete({
        "delete from template_dtl_medi",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into template_dtl_medi (template_id, medicine_id, ",
        "method, consumption, ",
        "frequency, is_deleted)",
        "values (#{templateId,jdbcType=INTEGER}, #{medicineId,jdbcType=INTEGER}, ",
        "#{method,jdbcType=VARCHAR}, #{consumption,jdbcType=VARCHAR}, ",
        "#{frequency,jdbcType=VARCHAR}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TemplateDtlMedi record);

    @InsertProvider(type=TemplateDtlMediSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TemplateDtlMedi record);

    @SelectProvider(type=TemplateDtlMediSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="template_id", property="templateId", jdbcType=JdbcType.INTEGER),
        @Result(column="medicine_id", property="medicineId", jdbcType=JdbcType.INTEGER),
        @Result(column="method", property="method", jdbcType=JdbcType.VARCHAR),
        @Result(column="consumption", property="consumption", jdbcType=JdbcType.VARCHAR),
        @Result(column="frequency", property="frequency", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<TemplateDtlMedi> selectByExample(TemplateDtlMediExample example);

    @Select({
        "select",
        "id, template_id, medicine_id, method, consumption, frequency, is_deleted",
        "from template_dtl_medi",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="template_id", property="templateId", jdbcType=JdbcType.INTEGER),
        @Result(column="medicine_id", property="medicineId", jdbcType=JdbcType.INTEGER),
        @Result(column="method", property="method", jdbcType=JdbcType.VARCHAR),
        @Result(column="consumption", property="consumption", jdbcType=JdbcType.VARCHAR),
        @Result(column="frequency", property="frequency", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    TemplateDtlMedi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateDtlMedi selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=TemplateDtlMediSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TemplateDtlMedi record, @Param("example") TemplateDtlMediExample example);

    @UpdateProvider(type=TemplateDtlMediSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TemplateDtlMedi record, @Param("example") TemplateDtlMediExample example);

    @UpdateProvider(type=TemplateDtlMediSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TemplateDtlMedi record);

    @Update({
        "update template_dtl_medi",
        "set template_id = #{templateId,jdbcType=INTEGER},",
          "medicine_id = #{medicineId,jdbcType=INTEGER},",
          "method = #{method,jdbcType=VARCHAR},",
          "consumption = #{consumption,jdbcType=VARCHAR},",
          "frequency = #{frequency,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TemplateDtlMedi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateDtlMediExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}