package com.neu.his.Dao;

import com.neu.his.entity.TemplateDtlHerb;
import com.neu.his.entity.TemplateDtlHerbExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TemplateDtlHerbMapper {
    @SelectProvider(type=TemplateDtlHerbSqlProvider.class, method="countByExample")
    long countByExample(TemplateDtlHerbExample example);

    @DeleteProvider(type=TemplateDtlHerbSqlProvider.class, method="deleteByExample")
    int deleteByExample(TemplateDtlHerbExample example);

    @Delete({
        "delete from template_dtl_herb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into template_dtl_herb (template_id, herb_id, ",
        "consumption, unit, ",
        "description, is_deleted)",
        "values (#{templateId,jdbcType=INTEGER}, #{herbId,jdbcType=INTEGER}, ",
        "#{consumption,jdbcType=VARCHAR}, #{unit,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TemplateDtlHerb record);

    @InsertProvider(type=TemplateDtlHerbSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TemplateDtlHerb record);

    @SelectProvider(type=TemplateDtlHerbSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="template_id", property="templateId", jdbcType=JdbcType.INTEGER),
        @Result(column="herb_id", property="herbId", jdbcType=JdbcType.INTEGER),
        @Result(column="consumption", property="consumption", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<TemplateDtlHerb> selectByExample(TemplateDtlHerbExample example);

    @Select({
        "select",
        "id, template_id, herb_id, consumption, unit, description, is_deleted",
        "from template_dtl_herb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="template_id", property="templateId", jdbcType=JdbcType.INTEGER),
        @Result(column="herb_id", property="herbId", jdbcType=JdbcType.INTEGER),
        @Result(column="consumption", property="consumption", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    TemplateDtlHerb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateDtlHerb selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=TemplateDtlHerbSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TemplateDtlHerb record, @Param("example") TemplateDtlHerbExample example);

    @UpdateProvider(type=TemplateDtlHerbSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TemplateDtlHerb record, @Param("example") TemplateDtlHerbExample example);

    @UpdateProvider(type=TemplateDtlHerbSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TemplateDtlHerb record);

    @Update({
        "update template_dtl_herb",
        "set template_id = #{templateId,jdbcType=INTEGER},",
          "herb_id = #{herbId,jdbcType=INTEGER},",
          "consumption = #{consumption,jdbcType=VARCHAR},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TemplateDtlHerb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateDtlHerbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}