package com.neu.his.Dao;

import com.neu.his.entity.TemplateNonDrug;
import com.neu.his.entity.TemplateNonDrugExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TemplateNonDrugMapper {
    @SelectProvider(type=TemplateNonDrugSqlProvider.class, method="countByExample")
    long countByExample(TemplateNonDrugExample example);

    @DeleteProvider(type=TemplateNonDrugSqlProvider.class, method="deleteByExample")
    int deleteByExample(TemplateNonDrugExample example);

    @Delete({
        "delete from template_non_drug",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into template_non_drug (name, doctor_id, ",
        "create_time, range, ",
        "record_category, is_deleted)",
        "values (#{name,jdbcType=VARCHAR}, #{doctorId,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{range,jdbcType=VARCHAR}, ",
        "#{recordCategory,jdbcType=INTEGER}, #{isDeleted,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TemplateNonDrug record);

    @InsertProvider(type=TemplateNonDrugSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TemplateNonDrug record);

    @SelectProvider(type=TemplateNonDrugSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="doctor_id", property="doctorId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="range", property="range", jdbcType=JdbcType.VARCHAR),
        @Result(column="record_category", property="recordCategory", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    List<TemplateNonDrug> selectByExample(TemplateNonDrugExample example);

    @Select({
        "select",
        "id, name, doctor_id, create_time, range, record_category, is_deleted",
        "from template_non_drug",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="doctor_id", property="doctorId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="range", property="range", jdbcType=JdbcType.VARCHAR),
        @Result(column="record_category", property="recordCategory", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.BIT)
    })
    TemplateNonDrug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateNonDrug selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    @UpdateProvider(type=TemplateNonDrugSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TemplateNonDrug record, @Param("example") TemplateNonDrugExample example);

    @UpdateProvider(type=TemplateNonDrugSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TemplateNonDrug record, @Param("example") TemplateNonDrugExample example);

    @UpdateProvider(type=TemplateNonDrugSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TemplateNonDrug record);

    @Update({
        "update template_non_drug",
        "set name = #{name,jdbcType=VARCHAR},",
          "doctor_id = #{doctorId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "range = #{range,jdbcType=VARCHAR},",
          "record_category = #{recordCategory,jdbcType=INTEGER},",
          "is_deleted = #{isDeleted,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TemplateNonDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateNonDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}