package org.neu.his.entity;

import java.io.Serializable;

public class Disease implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String code;

    private String desease_name;

    private String ICD;

    private Integer category_id;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Disease withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public Disease withCode(String code) {
        this.setCode(code);
        return this;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDesease_name() {
        return desease_name;
    }

    public Disease withDesease_name(String desease_name) {
        this.setDesease_name(desease_name);
        return this;
    }

    public void setDesease_name(String desease_name) {
        this.desease_name = desease_name;
    }

    public String getICD() {
        return ICD;
    }

    public Disease withICD(String ICD) {
        this.setICD(ICD);
        return this;
    }

    public void setICD(String ICD) {
        this.ICD = ICD;
    }

    public Integer getCategory_id() {
        return category_id;
    }

    public Disease withCategory_id(Integer category_id) {
        this.setCategory_id(category_id);
        return this;
    }

    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public Disease withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", desease_name=").append(desease_name);
        sb.append(", ICD=").append(ICD);
        sb.append(", category_id=").append(category_id);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Disease other = (Disease) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getDesease_name() == null ? other.getDesease_name() == null : this.getDesease_name().equals(other.getDesease_name()))
            && (this.getICD() == null ? other.getICD() == null : this.getICD().equals(other.getICD()))
            && (this.getCategory_id() == null ? other.getCategory_id() == null : this.getCategory_id().equals(other.getCategory_id()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getDesease_name() == null) ? 0 : getDesease_name().hashCode());
        result = prime * result + ((getICD() == null) ? 0 : getICD().hashCode());
        result = prime * result + ((getCategory_id() == null) ? 0 : getCategory_id().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}