package org.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class Drug implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String code;

    private String drug_name;

    private String standard;

    private String unit;

    private String factory;

    private Integer dosage;

    private Integer type_id;

    private Double unit_price;

    private String pinyin_mnemonic_code;

    private Date create_time;

    private Date last_edit_time;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Drug withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public Drug withCode(String code) {
        this.setCode(code);
        return this;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDrug_name() {
        return drug_name;
    }

    public Drug withDrug_name(String drug_name) {
        this.setDrug_name(drug_name);
        return this;
    }

    public void setDrug_name(String drug_name) {
        this.drug_name = drug_name;
    }

    public String getStandard() {
        return standard;
    }

    public Drug withStandard(String standard) {
        this.setStandard(standard);
        return this;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    public String getUnit() {
        return unit;
    }

    public Drug withUnit(String unit) {
        this.setUnit(unit);
        return this;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getFactory() {
        return factory;
    }

    public Drug withFactory(String factory) {
        this.setFactory(factory);
        return this;
    }

    public void setFactory(String factory) {
        this.factory = factory;
    }

    public Integer getDosage() {
        return dosage;
    }

    public Drug withDosage(Integer dosage) {
        this.setDosage(dosage);
        return this;
    }

    public void setDosage(Integer dosage) {
        this.dosage = dosage;
    }

    public Integer getType_id() {
        return type_id;
    }

    public Drug withType_id(Integer type_id) {
        this.setType_id(type_id);
        return this;
    }

    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    public Double getUnit_price() {
        return unit_price;
    }

    public Drug withUnit_price(Double unit_price) {
        this.setUnit_price(unit_price);
        return this;
    }

    public void setUnit_price(Double unit_price) {
        this.unit_price = unit_price;
    }

    public String getPinyin_mnemonic_code() {
        return pinyin_mnemonic_code;
    }

    public Drug withPinyin_mnemonic_code(String pinyin_mnemonic_code) {
        this.setPinyin_mnemonic_code(pinyin_mnemonic_code);
        return this;
    }

    public void setPinyin_mnemonic_code(String pinyin_mnemonic_code) {
        this.pinyin_mnemonic_code = pinyin_mnemonic_code;
    }

    public Date getCreate_time() {
        return create_time;
    }

    public Drug withCreate_time(Date create_time) {
        this.setCreate_time(create_time);
        return this;
    }

    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    public Date getLast_edit_time() {
        return last_edit_time;
    }

    public Drug withLast_edit_time(Date last_edit_time) {
        this.setLast_edit_time(last_edit_time);
        return this;
    }

    public void setLast_edit_time(Date last_edit_time) {
        this.last_edit_time = last_edit_time;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public Drug withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", drug_name=").append(drug_name);
        sb.append(", standard=").append(standard);
        sb.append(", unit=").append(unit);
        sb.append(", factory=").append(factory);
        sb.append(", dosage=").append(dosage);
        sb.append(", type_id=").append(type_id);
        sb.append(", unit_price=").append(unit_price);
        sb.append(", pinyin_mnemonic_code=").append(pinyin_mnemonic_code);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_edit_time=").append(last_edit_time);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Drug other = (Drug) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getDrug_name() == null ? other.getDrug_name() == null : this.getDrug_name().equals(other.getDrug_name()))
            && (this.getStandard() == null ? other.getStandard() == null : this.getStandard().equals(other.getStandard()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getFactory() == null ? other.getFactory() == null : this.getFactory().equals(other.getFactory()))
            && (this.getDosage() == null ? other.getDosage() == null : this.getDosage().equals(other.getDosage()))
            && (this.getType_id() == null ? other.getType_id() == null : this.getType_id().equals(other.getType_id()))
            && (this.getUnit_price() == null ? other.getUnit_price() == null : this.getUnit_price().equals(other.getUnit_price()))
            && (this.getPinyin_mnemonic_code() == null ? other.getPinyin_mnemonic_code() == null : this.getPinyin_mnemonic_code().equals(other.getPinyin_mnemonic_code()))
            && (this.getCreate_time() == null ? other.getCreate_time() == null : this.getCreate_time().equals(other.getCreate_time()))
            && (this.getLast_edit_time() == null ? other.getLast_edit_time() == null : this.getLast_edit_time().equals(other.getLast_edit_time()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getDrug_name() == null) ? 0 : getDrug_name().hashCode());
        result = prime * result + ((getStandard() == null) ? 0 : getStandard().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getFactory() == null) ? 0 : getFactory().hashCode());
        result = prime * result + ((getDosage() == null) ? 0 : getDosage().hashCode());
        result = prime * result + ((getType_id() == null) ? 0 : getType_id().hashCode());
        result = prime * result + ((getUnit_price() == null) ? 0 : getUnit_price().hashCode());
        result = prime * result + ((getPinyin_mnemonic_code() == null) ? 0 : getPinyin_mnemonic_code().hashCode());
        result = prime * result + ((getCreate_time() == null) ? 0 : getCreate_time().hashCode());
        result = prime * result + ((getLast_edit_time() == null) ? 0 : getLast_edit_time().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}