package org.neu.his.entity;

import java.io.Serializable;
import java.util.Date;

public class NonDrugApplication implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table non_drug_application
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table non_drug_application
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer case_id;

    private Integer reg_id;

    private Integer item_id;

    private String item_name;

    private String requirement;

    private String check_part;

    private Boolean is_urgent;

    private Integer num;

    private Date generate_time;

    private Integer generate_doctor_id;

    private Integer checker_id;

    private Integer recorder_id;

    private Date check_time;

    private String check_result;

    private Date result_time;

    private Integer application_status;

    private Integer record_category;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public NonDrugApplication withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCase_id() {
        return case_id;
    }

    public NonDrugApplication withCase_id(Integer case_id) {
        this.setCase_id(case_id);
        return this;
    }

    public void setCase_id(Integer case_id) {
        this.case_id = case_id;
    }

    public Integer getReg_id() {
        return reg_id;
    }

    public NonDrugApplication withReg_id(Integer reg_id) {
        this.setReg_id(reg_id);
        return this;
    }

    public void setReg_id(Integer reg_id) {
        this.reg_id = reg_id;
    }

    public Integer getItem_id() {
        return item_id;
    }

    public NonDrugApplication withItem_id(Integer item_id) {
        this.setItem_id(item_id);
        return this;
    }

    public void setItem_id(Integer item_id) {
        this.item_id = item_id;
    }

    public String getItem_name() {
        return item_name;
    }

    public NonDrugApplication withItem_name(String item_name) {
        this.setItem_name(item_name);
        return this;
    }

    public void setItem_name(String item_name) {
        this.item_name = item_name;
    }

    public String getRequirement() {
        return requirement;
    }

    public NonDrugApplication withRequirement(String requirement) {
        this.setRequirement(requirement);
        return this;
    }

    public void setRequirement(String requirement) {
        this.requirement = requirement;
    }

    public String getCheck_part() {
        return check_part;
    }

    public NonDrugApplication withCheck_part(String check_part) {
        this.setCheck_part(check_part);
        return this;
    }

    public void setCheck_part(String check_part) {
        this.check_part = check_part;
    }

    public Boolean getIs_urgent() {
        return is_urgent;
    }

    public NonDrugApplication withIs_urgent(Boolean is_urgent) {
        this.setIs_urgent(is_urgent);
        return this;
    }

    public void setIs_urgent(Boolean is_urgent) {
        this.is_urgent = is_urgent;
    }

    public Integer getNum() {
        return num;
    }

    public NonDrugApplication withNum(Integer num) {
        this.setNum(num);
        return this;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public Date getGenerate_time() {
        return generate_time;
    }

    public NonDrugApplication withGenerate_time(Date generate_time) {
        this.setGenerate_time(generate_time);
        return this;
    }

    public void setGenerate_time(Date generate_time) {
        this.generate_time = generate_time;
    }

    public Integer getGenerate_doctor_id() {
        return generate_doctor_id;
    }

    public NonDrugApplication withGenerate_doctor_id(Integer generate_doctor_id) {
        this.setGenerate_doctor_id(generate_doctor_id);
        return this;
    }

    public void setGenerate_doctor_id(Integer generate_doctor_id) {
        this.generate_doctor_id = generate_doctor_id;
    }

    public Integer getChecker_id() {
        return checker_id;
    }

    public NonDrugApplication withChecker_id(Integer checker_id) {
        this.setChecker_id(checker_id);
        return this;
    }

    public void setChecker_id(Integer checker_id) {
        this.checker_id = checker_id;
    }

    public Integer getRecorder_id() {
        return recorder_id;
    }

    public NonDrugApplication withRecorder_id(Integer recorder_id) {
        this.setRecorder_id(recorder_id);
        return this;
    }

    public void setRecorder_id(Integer recorder_id) {
        this.recorder_id = recorder_id;
    }

    public Date getCheck_time() {
        return check_time;
    }

    public NonDrugApplication withCheck_time(Date check_time) {
        this.setCheck_time(check_time);
        return this;
    }

    public void setCheck_time(Date check_time) {
        this.check_time = check_time;
    }

    public String getCheck_result() {
        return check_result;
    }

    public NonDrugApplication withCheck_result(String check_result) {
        this.setCheck_result(check_result);
        return this;
    }

    public void setCheck_result(String check_result) {
        this.check_result = check_result;
    }

    public Date getResult_time() {
        return result_time;
    }

    public NonDrugApplication withResult_time(Date result_time) {
        this.setResult_time(result_time);
        return this;
    }

    public void setResult_time(Date result_time) {
        this.result_time = result_time;
    }

    public Integer getApplication_status() {
        return application_status;
    }

    public NonDrugApplication withApplication_status(Integer application_status) {
        this.setApplication_status(application_status);
        return this;
    }

    public void setApplication_status(Integer application_status) {
        this.application_status = application_status;
    }

    public Integer getRecord_category() {
        return record_category;
    }

    public NonDrugApplication withRecord_category(Integer record_category) {
        this.setRecord_category(record_category);
        return this;
    }

    public void setRecord_category(Integer record_category) {
        this.record_category = record_category;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public NonDrugApplication withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", case_id=").append(case_id);
        sb.append(", reg_id=").append(reg_id);
        sb.append(", item_id=").append(item_id);
        sb.append(", item_name=").append(item_name);
        sb.append(", requirement=").append(requirement);
        sb.append(", check_part=").append(check_part);
        sb.append(", is_urgent=").append(is_urgent);
        sb.append(", num=").append(num);
        sb.append(", generate_time=").append(generate_time);
        sb.append(", generate_doctor_id=").append(generate_doctor_id);
        sb.append(", checker_id=").append(checker_id);
        sb.append(", recorder_id=").append(recorder_id);
        sb.append(", check_time=").append(check_time);
        sb.append(", check_result=").append(check_result);
        sb.append(", result_time=").append(result_time);
        sb.append(", application_status=").append(application_status);
        sb.append(", record_category=").append(record_category);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_application
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NonDrugApplication other = (NonDrugApplication) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCase_id() == null ? other.getCase_id() == null : this.getCase_id().equals(other.getCase_id()))
            && (this.getReg_id() == null ? other.getReg_id() == null : this.getReg_id().equals(other.getReg_id()))
            && (this.getItem_id() == null ? other.getItem_id() == null : this.getItem_id().equals(other.getItem_id()))
            && (this.getItem_name() == null ? other.getItem_name() == null : this.getItem_name().equals(other.getItem_name()))
            && (this.getRequirement() == null ? other.getRequirement() == null : this.getRequirement().equals(other.getRequirement()))
            && (this.getCheck_part() == null ? other.getCheck_part() == null : this.getCheck_part().equals(other.getCheck_part()))
            && (this.getIs_urgent() == null ? other.getIs_urgent() == null : this.getIs_urgent().equals(other.getIs_urgent()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getGenerate_time() == null ? other.getGenerate_time() == null : this.getGenerate_time().equals(other.getGenerate_time()))
            && (this.getGenerate_doctor_id() == null ? other.getGenerate_doctor_id() == null : this.getGenerate_doctor_id().equals(other.getGenerate_doctor_id()))
            && (this.getChecker_id() == null ? other.getChecker_id() == null : this.getChecker_id().equals(other.getChecker_id()))
            && (this.getRecorder_id() == null ? other.getRecorder_id() == null : this.getRecorder_id().equals(other.getRecorder_id()))
            && (this.getCheck_time() == null ? other.getCheck_time() == null : this.getCheck_time().equals(other.getCheck_time()))
            && (this.getCheck_result() == null ? other.getCheck_result() == null : this.getCheck_result().equals(other.getCheck_result()))
            && (this.getResult_time() == null ? other.getResult_time() == null : this.getResult_time().equals(other.getResult_time()))
            && (this.getApplication_status() == null ? other.getApplication_status() == null : this.getApplication_status().equals(other.getApplication_status()))
            && (this.getRecord_category() == null ? other.getRecord_category() == null : this.getRecord_category().equals(other.getRecord_category()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCase_id() == null) ? 0 : getCase_id().hashCode());
        result = prime * result + ((getReg_id() == null) ? 0 : getReg_id().hashCode());
        result = prime * result + ((getItem_id() == null) ? 0 : getItem_id().hashCode());
        result = prime * result + ((getItem_name() == null) ? 0 : getItem_name().hashCode());
        result = prime * result + ((getRequirement() == null) ? 0 : getRequirement().hashCode());
        result = prime * result + ((getCheck_part() == null) ? 0 : getCheck_part().hashCode());
        result = prime * result + ((getIs_urgent() == null) ? 0 : getIs_urgent().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getGenerate_time() == null) ? 0 : getGenerate_time().hashCode());
        result = prime * result + ((getGenerate_doctor_id() == null) ? 0 : getGenerate_doctor_id().hashCode());
        result = prime * result + ((getChecker_id() == null) ? 0 : getChecker_id().hashCode());
        result = prime * result + ((getRecorder_id() == null) ? 0 : getRecorder_id().hashCode());
        result = prime * result + ((getCheck_time() == null) ? 0 : getCheck_time().hashCode());
        result = prime * result + ((getCheck_result() == null) ? 0 : getCheck_result().hashCode());
        result = prime * result + ((getResult_time() == null) ? 0 : getResult_time().hashCode());
        result = prime * result + ((getApplication_status() == null) ? 0 : getApplication_status().hashCode());
        result = prime * result + ((getRecord_category() == null) ? 0 : getRecord_category().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}