package org.neu.his.entity;

import java.io.Serializable;

public class PrescriptionHerbDtl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer prescription_id;

    private Integer herb_id;

    private String consumption;

    private Double unit_price;

    private String description;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public PrescriptionHerbDtl withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPrescription_id() {
        return prescription_id;
    }

    public PrescriptionHerbDtl withPrescription_id(Integer prescription_id) {
        this.setPrescription_id(prescription_id);
        return this;
    }

    public void setPrescription_id(Integer prescription_id) {
        this.prescription_id = prescription_id;
    }

    public Integer getHerb_id() {
        return herb_id;
    }

    public PrescriptionHerbDtl withHerb_id(Integer herb_id) {
        this.setHerb_id(herb_id);
        return this;
    }

    public void setHerb_id(Integer herb_id) {
        this.herb_id = herb_id;
    }

    public String getConsumption() {
        return consumption;
    }

    public PrescriptionHerbDtl withConsumption(String consumption) {
        this.setConsumption(consumption);
        return this;
    }

    public void setConsumption(String consumption) {
        this.consumption = consumption;
    }

    public Double getUnit_price() {
        return unit_price;
    }

    public PrescriptionHerbDtl withUnit_price(Double unit_price) {
        this.setUnit_price(unit_price);
        return this;
    }

    public void setUnit_price(Double unit_price) {
        this.unit_price = unit_price;
    }

    public String getDescription() {
        return description;
    }

    public PrescriptionHerbDtl withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public PrescriptionHerbDtl withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", prescription_id=").append(prescription_id);
        sb.append(", herb_id=").append(herb_id);
        sb.append(", consumption=").append(consumption);
        sb.append(", unit_price=").append(unit_price);
        sb.append(", description=").append(description);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PrescriptionHerbDtl other = (PrescriptionHerbDtl) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPrescription_id() == null ? other.getPrescription_id() == null : this.getPrescription_id().equals(other.getPrescription_id()))
            && (this.getHerb_id() == null ? other.getHerb_id() == null : this.getHerb_id().equals(other.getHerb_id()))
            && (this.getConsumption() == null ? other.getConsumption() == null : this.getConsumption().equals(other.getConsumption()))
            && (this.getUnit_price() == null ? other.getUnit_price() == null : this.getUnit_price().equals(other.getUnit_price()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPrescription_id() == null) ? 0 : getPrescription_id().hashCode());
        result = prime * result + ((getHerb_id() == null) ? 0 : getHerb_id().hashCode());
        result = prime * result + ((getConsumption() == null) ? 0 : getConsumption().hashCode());
        result = prime * result + ((getUnit_price() == null) ? 0 : getUnit_price().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}