package org.neu.his.entity;

import java.io.Serializable;

public class ScheduleRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String rule_name;

    private Integer dept_id;

    private Integer doctor_id;

    private String days;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public ScheduleRule withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRule_name() {
        return rule_name;
    }

    public ScheduleRule withRule_name(String rule_name) {
        this.setRule_name(rule_name);
        return this;
    }

    public void setRule_name(String rule_name) {
        this.rule_name = rule_name;
    }

    public Integer getDept_id() {
        return dept_id;
    }

    public ScheduleRule withDept_id(Integer dept_id) {
        this.setDept_id(dept_id);
        return this;
    }

    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }

    public Integer getDoctor_id() {
        return doctor_id;
    }

    public ScheduleRule withDoctor_id(Integer doctor_id) {
        this.setDoctor_id(doctor_id);
        return this;
    }

    public void setDoctor_id(Integer doctor_id) {
        this.doctor_id = doctor_id;
    }

    public String getDays() {
        return days;
    }

    public ScheduleRule withDays(String days) {
        this.setDays(days);
        return this;
    }

    public void setDays(String days) {
        this.days = days;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public ScheduleRule withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rule_name=").append(rule_name);
        sb.append(", dept_id=").append(dept_id);
        sb.append(", doctor_id=").append(doctor_id);
        sb.append(", days=").append(days);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScheduleRule other = (ScheduleRule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRule_name() == null ? other.getRule_name() == null : this.getRule_name().equals(other.getRule_name()))
            && (this.getDept_id() == null ? other.getDept_id() == null : this.getDept_id().equals(other.getDept_id()))
            && (this.getDoctor_id() == null ? other.getDoctor_id() == null : this.getDoctor_id().equals(other.getDoctor_id()))
            && (this.getDays() == null ? other.getDays() == null : this.getDays().equals(other.getDays()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRule_name() == null) ? 0 : getRule_name().hashCode());
        result = prime * result + ((getDept_id() == null) ? 0 : getDept_id().hashCode());
        result = prime * result + ((getDoctor_id() == null) ? 0 : getDoctor_id().hashCode());
        result = prime * result + ((getDays() == null) ? 0 : getDays().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}