package org.neu.his.entity;

import java.io.Serializable;

public class TemplateDtlMedi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer template_id;

    private Integer medicine_id;

    private String method;

    private String consumption;

    private String frequency;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public TemplateDtlMedi withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTemplate_id() {
        return template_id;
    }

    public TemplateDtlMedi withTemplate_id(Integer template_id) {
        this.setTemplate_id(template_id);
        return this;
    }

    public void setTemplate_id(Integer template_id) {
        this.template_id = template_id;
    }

    public Integer getMedicine_id() {
        return medicine_id;
    }

    public TemplateDtlMedi withMedicine_id(Integer medicine_id) {
        this.setMedicine_id(medicine_id);
        return this;
    }

    public void setMedicine_id(Integer medicine_id) {
        this.medicine_id = medicine_id;
    }

    public String getMethod() {
        return method;
    }

    public TemplateDtlMedi withMethod(String method) {
        this.setMethod(method);
        return this;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getConsumption() {
        return consumption;
    }

    public TemplateDtlMedi withConsumption(String consumption) {
        this.setConsumption(consumption);
        return this;
    }

    public void setConsumption(String consumption) {
        this.consumption = consumption;
    }

    public String getFrequency() {
        return frequency;
    }

    public TemplateDtlMedi withFrequency(String frequency) {
        this.setFrequency(frequency);
        return this;
    }

    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public TemplateDtlMedi withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", template_id=").append(template_id);
        sb.append(", medicine_id=").append(medicine_id);
        sb.append(", method=").append(method);
        sb.append(", consumption=").append(consumption);
        sb.append(", frequency=").append(frequency);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_medi
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TemplateDtlMedi other = (TemplateDtlMedi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTemplate_id() == null ? other.getTemplate_id() == null : this.getTemplate_id().equals(other.getTemplate_id()))
            && (this.getMedicine_id() == null ? other.getMedicine_id() == null : this.getMedicine_id().equals(other.getMedicine_id()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getConsumption() == null ? other.getConsumption() == null : this.getConsumption().equals(other.getConsumption()))
            && (this.getFrequency() == null ? other.getFrequency() == null : this.getFrequency().equals(other.getFrequency()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTemplate_id() == null) ? 0 : getTemplate_id().hashCode());
        result = prime * result + ((getMedicine_id() == null) ? 0 : getMedicine_id().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getConsumption() == null) ? 0 : getConsumption().hashCode());
        result = prime * result + ((getFrequency() == null) ? 0 : getFrequency().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}