package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.CategoryConstant;
import org.neu.his.entity.CategoryConstantExample;

@Mapper
public interface CategoryConstantMapper {
    long countByExample(CategoryConstantExample example);

    int deleteByExample(CategoryConstantExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CategoryConstant record);

    int insertSelective(CategoryConstant record);

    List<CategoryConstant> selectByExample(CategoryConstantExample example);

    CategoryConstant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CategoryConstant selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") CategoryConstant record, @Param("example") CategoryConstantExample example);

    int updateByExample(@Param("record") CategoryConstant record, @Param("example") CategoryConstantExample example);

    int updateByPrimaryKeySelective(CategoryConstant record);

    int updateByPrimaryKey(CategoryConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") CategoryConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}