package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.NonDrugApplication;
import org.neu.his.entity.NonDrugApplicationExample;

@Mapper
public interface NonDrugApplicationMapper {
    long countByExample(NonDrugApplicationExample example);

    int deleteByExample(NonDrugApplicationExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(NonDrugApplication record);

    int insertSelective(NonDrugApplication record);

    List<NonDrugApplication> selectByExample(NonDrugApplicationExample example);

    NonDrugApplication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_application
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NonDrugApplication selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") NonDrugApplication record, @Param("example") NonDrugApplicationExample example);

    int updateByExample(@Param("record") NonDrugApplication record, @Param("example") NonDrugApplicationExample example);

    int updateByPrimaryKeySelective(NonDrugApplication record);

    int updateByPrimaryKey(NonDrugApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_application
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") NonDrugApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_application
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}