package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.OperatorSettlement;
import org.neu.his.entity.OperatorSettlementExample;

@Mapper
public interface OperatorSettlementMapper {
    long countByExample(OperatorSettlementExample example);

    int deleteByExample(OperatorSettlementExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(OperatorSettlement record);

    int insertSelective(OperatorSettlement record);

    List<OperatorSettlement> selectByExample(OperatorSettlementExample example);

    OperatorSettlement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OperatorSettlement selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") OperatorSettlement record, @Param("example") OperatorSettlementExample example);

    int updateByExample(@Param("record") OperatorSettlement record, @Param("example") OperatorSettlementExample example);

    int updateByPrimaryKeySelective(OperatorSettlement record);

    int updateByPrimaryKey(OperatorSettlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") OperatorSettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_settlement
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}