package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.PrescriptionMedicineDtl;
import org.neu.his.entity.PrescriptionMedicineDtlExample;

@Mapper
public interface PrescriptionMedicineDtlMapper {
    long countByExample(PrescriptionMedicineDtlExample example);

    int deleteByExample(PrescriptionMedicineDtlExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PrescriptionMedicineDtl record);

    int insertSelective(PrescriptionMedicineDtl record);

    List<PrescriptionMedicineDtl> selectByExample(PrescriptionMedicineDtlExample example);

    PrescriptionMedicineDtl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PrescriptionMedicineDtl selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PrescriptionMedicineDtl record, @Param("example") PrescriptionMedicineDtlExample example);

    int updateByExample(@Param("record") PrescriptionMedicineDtl record, @Param("example") PrescriptionMedicineDtlExample example);

    int updateByPrimaryKeySelective(PrescriptionMedicineDtl record);

    int updateByPrimaryKey(PrescriptionMedicineDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PrescriptionMedicineDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_medicine_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}