package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.PrescriptionHerb;
import org.neu.his.entity.PrescriptionHerbExample;

@Mapper
public interface PrescriptionHerbMapper {
    long countByExample(PrescriptionHerbExample example);

    int deleteByExample(PrescriptionHerbExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PrescriptionHerb record);

    int insertSelective(PrescriptionHerb record);

    List<PrescriptionHerb> selectByExample(PrescriptionHerbExample example);

    PrescriptionHerb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PrescriptionHerb selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PrescriptionHerb record, @Param("example") PrescriptionHerbExample example);

    int updateByExample(@Param("record") PrescriptionHerb record, @Param("example") PrescriptionHerbExample example);

    int updateByPrimaryKeySelective(PrescriptionHerb record);

    int updateByPrimaryKey(PrescriptionHerb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PrescriptionHerbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}