package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.TemplateDtlHerb;
import org.neu.his.entity.TemplateDtlHerbExample;

@Mapper
public interface TemplateDtlHerbMapper {
    long countByExample(TemplateDtlHerbExample example);

    int deleteByExample(TemplateDtlHerbExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TemplateDtlHerb record);

    int insertSelective(TemplateDtlHerb record);

    List<TemplateDtlHerb> selectByExample(TemplateDtlHerbExample example);

    TemplateDtlHerb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateDtlHerb selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") TemplateDtlHerb record, @Param("example") TemplateDtlHerbExample example);

    int updateByExample(@Param("record") TemplateDtlHerb record, @Param("example") TemplateDtlHerbExample example);

    int updateByPrimaryKeySelective(TemplateDtlHerb record);

    int updateByPrimaryKey(TemplateDtlHerb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateDtlHerbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}