package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.TemplateDtlNonDrug;
import org.neu.his.entity.TemplateDtlNonDrugExample;

@Mapper
public interface TemplateDtlNonDrugMapper {
    long countByExample(TemplateDtlNonDrugExample example);

    int deleteByExample(TemplateDtlNonDrugExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TemplateDtlNonDrug record);

    int insertSelective(TemplateDtlNonDrug record);

    List<TemplateDtlNonDrug> selectByExample(TemplateDtlNonDrugExample example);

    TemplateDtlNonDrug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateDtlNonDrug selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") TemplateDtlNonDrug record, @Param("example") TemplateDtlNonDrugExample example);

    int updateByExample(@Param("record") TemplateDtlNonDrug record, @Param("example") TemplateDtlNonDrugExample example);

    int updateByPrimaryKeySelective(TemplateDtlNonDrug record);

    int updateByPrimaryKey(TemplateDtlNonDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateDtlNonDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_dtl_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}