package org.neu.his.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.neu.his.entity.TemplateNonDrug;
import org.neu.his.entity.TemplateNonDrugExample;

@Mapper
public interface TemplateNonDrugMapper {
    long countByExample(TemplateNonDrugExample example);

    int deleteByExample(TemplateNonDrugExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TemplateNonDrug record);

    int insertSelective(TemplateNonDrug record);

    List<TemplateNonDrug> selectByExample(TemplateNonDrugExample example);

    TemplateNonDrug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TemplateNonDrug selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") TemplateNonDrug record, @Param("example") TemplateNonDrugExample example);

    int updateByExample(@Param("record") TemplateNonDrug record, @Param("example") TemplateNonDrugExample example);

    int updateByPrimaryKeySelective(TemplateNonDrug record);

    int updateByPrimaryKey(TemplateNonDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TemplateNonDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_non_drug
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}