package org.neu.entity;

import java.io.Serializable;

public class CategoryDisease implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String code;

    private String category_name;

    private String sequence;

    private Integer disease_flag;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public CategoryDisease withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public CategoryDisease withCode(String code) {
        this.setCode(code);
        return this;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCategory_name() {
        return category_name;
    }

    public CategoryDisease withCategory_name(String category_name) {
        this.setCategory_name(category_name);
        return this;
    }

    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    public String getSequence() {
        return sequence;
    }

    public CategoryDisease withSequence(String sequence) {
        this.setSequence(sequence);
        return this;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public Integer getDisease_flag() {
        return disease_flag;
    }

    public CategoryDisease withDisease_flag(Integer disease_flag) {
        this.setDisease_flag(disease_flag);
        return this;
    }

    public void setDisease_flag(Integer disease_flag) {
        this.disease_flag = disease_flag;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public CategoryDisease withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", category_name=").append(category_name);
        sb.append(", sequence=").append(sequence);
        sb.append(", disease_flag=").append(disease_flag);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_disease
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CategoryDisease other = (CategoryDisease) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCategory_name() == null ? other.getCategory_name() == null : this.getCategory_name().equals(other.getCategory_name()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getDisease_flag() == null ? other.getDisease_flag() == null : this.getDisease_flag().equals(other.getDisease_flag()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCategory_name() == null) ? 0 : getCategory_name().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getDisease_flag() == null) ? 0 : getDisease_flag().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}