package org.neu.entity;

import java.io.Serializable;

public class CategoryReg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String code;

    private String category_name;

    private String sequence;

    private Double reg_amount;

    private Integer reg_limit;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public CategoryReg withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public CategoryReg withCode(String code) {
        this.setCode(code);
        return this;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCategory_name() {
        return category_name;
    }

    public CategoryReg withCategory_name(String category_name) {
        this.setCategory_name(category_name);
        return this;
    }

    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    public String getSequence() {
        return sequence;
    }

    public CategoryReg withSequence(String sequence) {
        this.setSequence(sequence);
        return this;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public Double getReg_amount() {
        return reg_amount;
    }

    public CategoryReg withReg_amount(Double reg_amount) {
        this.setReg_amount(reg_amount);
        return this;
    }

    public void setReg_amount(Double reg_amount) {
        this.reg_amount = reg_amount;
    }

    public Integer getReg_limit() {
        return reg_limit;
    }

    public CategoryReg withReg_limit(Integer reg_limit) {
        this.setReg_limit(reg_limit);
        return this;
    }

    public void setReg_limit(Integer reg_limit) {
        this.reg_limit = reg_limit;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public CategoryReg withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", category_name=").append(category_name);
        sb.append(", sequence=").append(sequence);
        sb.append(", reg_amount=").append(reg_amount);
        sb.append(", reg_limit=").append(reg_limit);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_reg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CategoryReg other = (CategoryReg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCategory_name() == null ? other.getCategory_name() == null : this.getCategory_name().equals(other.getCategory_name()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getReg_amount() == null ? other.getReg_amount() == null : this.getReg_amount().equals(other.getReg_amount()))
            && (this.getReg_limit() == null ? other.getReg_limit() == null : this.getReg_limit().equals(other.getReg_limit()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCategory_name() == null) ? 0 : getCategory_name().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getReg_amount() == null) ? 0 : getReg_amount().hashCode());
        result = prime * result + ((getReg_limit() == null) ? 0 : getReg_limit().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}