package org.neu.entity;

import java.io.Serializable;
import java.util.Date;

public class Diagnosis implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer case_id;

    private Integer reg_id;

    private Integer disease_id;

    private Boolean diagnosis_type;

    private Date onset_time;

    private Boolean diagnosis_class;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Diagnosis withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCase_id() {
        return case_id;
    }

    public Diagnosis withCase_id(Integer case_id) {
        this.setCase_id(case_id);
        return this;
    }

    public void setCase_id(Integer case_id) {
        this.case_id = case_id;
    }

    public Integer getReg_id() {
        return reg_id;
    }

    public Diagnosis withReg_id(Integer reg_id) {
        this.setReg_id(reg_id);
        return this;
    }

    public void setReg_id(Integer reg_id) {
        this.reg_id = reg_id;
    }

    public Integer getDisease_id() {
        return disease_id;
    }

    public Diagnosis withDisease_id(Integer disease_id) {
        this.setDisease_id(disease_id);
        return this;
    }

    public void setDisease_id(Integer disease_id) {
        this.disease_id = disease_id;
    }

    public Boolean getDiagnosis_type() {
        return diagnosis_type;
    }

    public Diagnosis withDiagnosis_type(Boolean diagnosis_type) {
        this.setDiagnosis_type(diagnosis_type);
        return this;
    }

    public void setDiagnosis_type(Boolean diagnosis_type) {
        this.diagnosis_type = diagnosis_type;
    }

    public Date getOnset_time() {
        return onset_time;
    }

    public Diagnosis withOnset_time(Date onset_time) {
        this.setOnset_time(onset_time);
        return this;
    }

    public void setOnset_time(Date onset_time) {
        this.onset_time = onset_time;
    }

    public Boolean getDiagnosis_class() {
        return diagnosis_class;
    }

    public Diagnosis withDiagnosis_class(Boolean diagnosis_class) {
        this.setDiagnosis_class(diagnosis_class);
        return this;
    }

    public void setDiagnosis_class(Boolean diagnosis_class) {
        this.diagnosis_class = diagnosis_class;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public Diagnosis withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", case_id=").append(case_id);
        sb.append(", reg_id=").append(reg_id);
        sb.append(", disease_id=").append(disease_id);
        sb.append(", diagnosis_type=").append(diagnosis_type);
        sb.append(", onset_time=").append(onset_time);
        sb.append(", diagnosis_class=").append(diagnosis_class);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Diagnosis other = (Diagnosis) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCase_id() == null ? other.getCase_id() == null : this.getCase_id().equals(other.getCase_id()))
            && (this.getReg_id() == null ? other.getReg_id() == null : this.getReg_id().equals(other.getReg_id()))
            && (this.getDisease_id() == null ? other.getDisease_id() == null : this.getDisease_id().equals(other.getDisease_id()))
            && (this.getDiagnosis_type() == null ? other.getDiagnosis_type() == null : this.getDiagnosis_type().equals(other.getDiagnosis_type()))
            && (this.getOnset_time() == null ? other.getOnset_time() == null : this.getOnset_time().equals(other.getOnset_time()))
            && (this.getDiagnosis_class() == null ? other.getDiagnosis_class() == null : this.getDiagnosis_class().equals(other.getDiagnosis_class()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCase_id() == null) ? 0 : getCase_id().hashCode());
        result = prime * result + ((getReg_id() == null) ? 0 : getReg_id().hashCode());
        result = prime * result + ((getDisease_id() == null) ? 0 : getDisease_id().hashCode());
        result = prime * result + ((getDiagnosis_type() == null) ? 0 : getDiagnosis_type().hashCode());
        result = prime * result + ((getOnset_time() == null) ? 0 : getOnset_time().hashCode());
        result = prime * result + ((getDiagnosis_class() == null) ? 0 : getDiagnosis_class().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}