package org.neu.entity;

import java.io.Serializable;
import java.util.Date;

public class PaymentDtl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer reg_id;

    private Integer invoice_no;

    private Integer item_id;

    private Boolean item_type;

    private String item_name;

    private Double item_unit_price;

    private Integer quantity;

    private Integer dept_id;

    private Date prescription_generation_time;

    private Integer generator_id;

    private Date payment_operation_time;

    private Integer operator_id;

    private String method;

    private Integer related_refund_id;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public PaymentDtl withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getReg_id() {
        return reg_id;
    }

    public PaymentDtl withReg_id(Integer reg_id) {
        this.setReg_id(reg_id);
        return this;
    }

    public void setReg_id(Integer reg_id) {
        this.reg_id = reg_id;
    }

    public Integer getInvoice_no() {
        return invoice_no;
    }

    public PaymentDtl withInvoice_no(Integer invoice_no) {
        this.setInvoice_no(invoice_no);
        return this;
    }

    public void setInvoice_no(Integer invoice_no) {
        this.invoice_no = invoice_no;
    }

    public Integer getItem_id() {
        return item_id;
    }

    public PaymentDtl withItem_id(Integer item_id) {
        this.setItem_id(item_id);
        return this;
    }

    public void setItem_id(Integer item_id) {
        this.item_id = item_id;
    }

    public Boolean getItem_type() {
        return item_type;
    }

    public PaymentDtl withItem_type(Boolean item_type) {
        this.setItem_type(item_type);
        return this;
    }

    public void setItem_type(Boolean item_type) {
        this.item_type = item_type;
    }

    public String getItem_name() {
        return item_name;
    }

    public PaymentDtl withItem_name(String item_name) {
        this.setItem_name(item_name);
        return this;
    }

    public void setItem_name(String item_name) {
        this.item_name = item_name;
    }

    public Double getItem_unit_price() {
        return item_unit_price;
    }

    public PaymentDtl withItem_unit_price(Double item_unit_price) {
        this.setItem_unit_price(item_unit_price);
        return this;
    }

    public void setItem_unit_price(Double item_unit_price) {
        this.item_unit_price = item_unit_price;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public PaymentDtl withQuantity(Integer quantity) {
        this.setQuantity(quantity);
        return this;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getDept_id() {
        return dept_id;
    }

    public PaymentDtl withDept_id(Integer dept_id) {
        this.setDept_id(dept_id);
        return this;
    }

    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }

    public Date getPrescription_generation_time() {
        return prescription_generation_time;
    }

    public PaymentDtl withPrescription_generation_time(Date prescription_generation_time) {
        this.setPrescription_generation_time(prescription_generation_time);
        return this;
    }

    public void setPrescription_generation_time(Date prescription_generation_time) {
        this.prescription_generation_time = prescription_generation_time;
    }

    public Integer getGenerator_id() {
        return generator_id;
    }

    public PaymentDtl withGenerator_id(Integer generator_id) {
        this.setGenerator_id(generator_id);
        return this;
    }

    public void setGenerator_id(Integer generator_id) {
        this.generator_id = generator_id;
    }

    public Date getPayment_operation_time() {
        return payment_operation_time;
    }

    public PaymentDtl withPayment_operation_time(Date payment_operation_time) {
        this.setPayment_operation_time(payment_operation_time);
        return this;
    }

    public void setPayment_operation_time(Date payment_operation_time) {
        this.payment_operation_time = payment_operation_time;
    }

    public Integer getOperator_id() {
        return operator_id;
    }

    public PaymentDtl withOperator_id(Integer operator_id) {
        this.setOperator_id(operator_id);
        return this;
    }

    public void setOperator_id(Integer operator_id) {
        this.operator_id = operator_id;
    }

    public String getMethod() {
        return method;
    }

    public PaymentDtl withMethod(String method) {
        this.setMethod(method);
        return this;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public Integer getRelated_refund_id() {
        return related_refund_id;
    }

    public PaymentDtl withRelated_refund_id(Integer related_refund_id) {
        this.setRelated_refund_id(related_refund_id);
        return this;
    }

    public void setRelated_refund_id(Integer related_refund_id) {
        this.related_refund_id = related_refund_id;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public PaymentDtl withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", reg_id=").append(reg_id);
        sb.append(", invoice_no=").append(invoice_no);
        sb.append(", item_id=").append(item_id);
        sb.append(", item_type=").append(item_type);
        sb.append(", item_name=").append(item_name);
        sb.append(", item_unit_price=").append(item_unit_price);
        sb.append(", quantity=").append(quantity);
        sb.append(", dept_id=").append(dept_id);
        sb.append(", prescription_generation_time=").append(prescription_generation_time);
        sb.append(", generator_id=").append(generator_id);
        sb.append(", payment_operation_time=").append(payment_operation_time);
        sb.append(", operator_id=").append(operator_id);
        sb.append(", method=").append(method);
        sb.append(", related_refund_id=").append(related_refund_id);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_dtl
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaymentDtl other = (PaymentDtl) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getReg_id() == null ? other.getReg_id() == null : this.getReg_id().equals(other.getReg_id()))
            && (this.getInvoice_no() == null ? other.getInvoice_no() == null : this.getInvoice_no().equals(other.getInvoice_no()))
            && (this.getItem_id() == null ? other.getItem_id() == null : this.getItem_id().equals(other.getItem_id()))
            && (this.getItem_type() == null ? other.getItem_type() == null : this.getItem_type().equals(other.getItem_type()))
            && (this.getItem_name() == null ? other.getItem_name() == null : this.getItem_name().equals(other.getItem_name()))
            && (this.getItem_unit_price() == null ? other.getItem_unit_price() == null : this.getItem_unit_price().equals(other.getItem_unit_price()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getDept_id() == null ? other.getDept_id() == null : this.getDept_id().equals(other.getDept_id()))
            && (this.getPrescription_generation_time() == null ? other.getPrescription_generation_time() == null : this.getPrescription_generation_time().equals(other.getPrescription_generation_time()))
            && (this.getGenerator_id() == null ? other.getGenerator_id() == null : this.getGenerator_id().equals(other.getGenerator_id()))
            && (this.getPayment_operation_time() == null ? other.getPayment_operation_time() == null : this.getPayment_operation_time().equals(other.getPayment_operation_time()))
            && (this.getOperator_id() == null ? other.getOperator_id() == null : this.getOperator_id().equals(other.getOperator_id()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getRelated_refund_id() == null ? other.getRelated_refund_id() == null : this.getRelated_refund_id().equals(other.getRelated_refund_id()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getReg_id() == null) ? 0 : getReg_id().hashCode());
        result = prime * result + ((getInvoice_no() == null) ? 0 : getInvoice_no().hashCode());
        result = prime * result + ((getItem_id() == null) ? 0 : getItem_id().hashCode());
        result = prime * result + ((getItem_type() == null) ? 0 : getItem_type().hashCode());
        result = prime * result + ((getItem_name() == null) ? 0 : getItem_name().hashCode());
        result = prime * result + ((getItem_unit_price() == null) ? 0 : getItem_unit_price().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getDept_id() == null) ? 0 : getDept_id().hashCode());
        result = prime * result + ((getPrescription_generation_time() == null) ? 0 : getPrescription_generation_time().hashCode());
        result = prime * result + ((getGenerator_id() == null) ? 0 : getGenerator_id().hashCode());
        result = prime * result + ((getPayment_operation_time() == null) ? 0 : getPayment_operation_time().hashCode());
        result = prime * result + ((getOperator_id() == null) ? 0 : getOperator_id().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getRelated_refund_id() == null) ? 0 : getRelated_refund_id().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}