package org.neu.entity;

import java.io.Serializable;
import java.util.Date;

public class Registration implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registration
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registration
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Integer case_no;

    private String patient_name;

    private Short sex;

    private String personal_id;

    private Date birthday;

    private Integer age;

    private String age_type;

    private String address;

    private Date see_date;

    private String noon;

    private Integer dept_id;

    private Integer doctor_id;

    private Integer reg_level_id;

    private String settlement_type;

    private Boolean need_case_book;

    private Date reg_time;

    private Integer operator;

    private Integer inspection_status;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Registration withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCase_no() {
        return case_no;
    }

    public Registration withCase_no(Integer case_no) {
        this.setCase_no(case_no);
        return this;
    }

    public void setCase_no(Integer case_no) {
        this.case_no = case_no;
    }

    public String getPatient_name() {
        return patient_name;
    }

    public Registration withPatient_name(String patient_name) {
        this.setPatient_name(patient_name);
        return this;
    }

    public void setPatient_name(String patient_name) {
        this.patient_name = patient_name;
    }

    public Short getSex() {
        return sex;
    }

    public Registration withSex(Short sex) {
        this.setSex(sex);
        return this;
    }

    public void setSex(Short sex) {
        this.sex = sex;
    }

    public String getPersonal_id() {
        return personal_id;
    }

    public Registration withPersonal_id(String personal_id) {
        this.setPersonal_id(personal_id);
        return this;
    }

    public void setPersonal_id(String personal_id) {
        this.personal_id = personal_id;
    }

    public Date getBirthday() {
        return birthday;
    }

    public Registration withBirthday(Date birthday) {
        this.setBirthday(birthday);
        return this;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Integer getAge() {
        return age;
    }

    public Registration withAge(Integer age) {
        this.setAge(age);
        return this;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getAge_type() {
        return age_type;
    }

    public Registration withAge_type(String age_type) {
        this.setAge_type(age_type);
        return this;
    }

    public void setAge_type(String age_type) {
        this.age_type = age_type;
    }

    public String getAddress() {
        return address;
    }

    public Registration withAddress(String address) {
        this.setAddress(address);
        return this;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getSee_date() {
        return see_date;
    }

    public Registration withSee_date(Date see_date) {
        this.setSee_date(see_date);
        return this;
    }

    public void setSee_date(Date see_date) {
        this.see_date = see_date;
    }

    public String getNoon() {
        return noon;
    }

    public Registration withNoon(String noon) {
        this.setNoon(noon);
        return this;
    }

    public void setNoon(String noon) {
        this.noon = noon;
    }

    public Integer getDept_id() {
        return dept_id;
    }

    public Registration withDept_id(Integer dept_id) {
        this.setDept_id(dept_id);
        return this;
    }

    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }

    public Integer getDoctor_id() {
        return doctor_id;
    }

    public Registration withDoctor_id(Integer doctor_id) {
        this.setDoctor_id(doctor_id);
        return this;
    }

    public void setDoctor_id(Integer doctor_id) {
        this.doctor_id = doctor_id;
    }

    public Integer getReg_level_id() {
        return reg_level_id;
    }

    public Registration withReg_level_id(Integer reg_level_id) {
        this.setReg_level_id(reg_level_id);
        return this;
    }

    public void setReg_level_id(Integer reg_level_id) {
        this.reg_level_id = reg_level_id;
    }

    public String getSettlement_type() {
        return settlement_type;
    }

    public Registration withSettlement_type(String settlement_type) {
        this.setSettlement_type(settlement_type);
        return this;
    }

    public void setSettlement_type(String settlement_type) {
        this.settlement_type = settlement_type;
    }

    public Boolean getNeed_case_book() {
        return need_case_book;
    }

    public Registration withNeed_case_book(Boolean need_case_book) {
        this.setNeed_case_book(need_case_book);
        return this;
    }

    public void setNeed_case_book(Boolean need_case_book) {
        this.need_case_book = need_case_book;
    }

    public Date getReg_time() {
        return reg_time;
    }

    public Registration withReg_time(Date reg_time) {
        this.setReg_time(reg_time);
        return this;
    }

    public void setReg_time(Date reg_time) {
        this.reg_time = reg_time;
    }

    public Integer getOperator() {
        return operator;
    }

    public Registration withOperator(Integer operator) {
        this.setOperator(operator);
        return this;
    }

    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    public Integer getInspection_status() {
        return inspection_status;
    }

    public Registration withInspection_status(Integer inspection_status) {
        this.setInspection_status(inspection_status);
        return this;
    }

    public void setInspection_status(Integer inspection_status) {
        this.inspection_status = inspection_status;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public Registration withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", case_no=").append(case_no);
        sb.append(", patient_name=").append(patient_name);
        sb.append(", sex=").append(sex);
        sb.append(", personal_id=").append(personal_id);
        sb.append(", birthday=").append(birthday);
        sb.append(", age=").append(age);
        sb.append(", age_type=").append(age_type);
        sb.append(", address=").append(address);
        sb.append(", see_date=").append(see_date);
        sb.append(", noon=").append(noon);
        sb.append(", dept_id=").append(dept_id);
        sb.append(", doctor_id=").append(doctor_id);
        sb.append(", reg_level_id=").append(reg_level_id);
        sb.append(", settlement_type=").append(settlement_type);
        sb.append(", need_case_book=").append(need_case_book);
        sb.append(", reg_time=").append(reg_time);
        sb.append(", operator=").append(operator);
        sb.append(", inspection_status=").append(inspection_status);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Registration other = (Registration) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCase_no() == null ? other.getCase_no() == null : this.getCase_no().equals(other.getCase_no()))
            && (this.getPatient_name() == null ? other.getPatient_name() == null : this.getPatient_name().equals(other.getPatient_name()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getPersonal_id() == null ? other.getPersonal_id() == null : this.getPersonal_id().equals(other.getPersonal_id()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getAge_type() == null ? other.getAge_type() == null : this.getAge_type().equals(other.getAge_type()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getSee_date() == null ? other.getSee_date() == null : this.getSee_date().equals(other.getSee_date()))
            && (this.getNoon() == null ? other.getNoon() == null : this.getNoon().equals(other.getNoon()))
            && (this.getDept_id() == null ? other.getDept_id() == null : this.getDept_id().equals(other.getDept_id()))
            && (this.getDoctor_id() == null ? other.getDoctor_id() == null : this.getDoctor_id().equals(other.getDoctor_id()))
            && (this.getReg_level_id() == null ? other.getReg_level_id() == null : this.getReg_level_id().equals(other.getReg_level_id()))
            && (this.getSettlement_type() == null ? other.getSettlement_type() == null : this.getSettlement_type().equals(other.getSettlement_type()))
            && (this.getNeed_case_book() == null ? other.getNeed_case_book() == null : this.getNeed_case_book().equals(other.getNeed_case_book()))
            && (this.getReg_time() == null ? other.getReg_time() == null : this.getReg_time().equals(other.getReg_time()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getInspection_status() == null ? other.getInspection_status() == null : this.getInspection_status().equals(other.getInspection_status()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCase_no() == null) ? 0 : getCase_no().hashCode());
        result = prime * result + ((getPatient_name() == null) ? 0 : getPatient_name().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getPersonal_id() == null) ? 0 : getPersonal_id().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getAge_type() == null) ? 0 : getAge_type().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getSee_date() == null) ? 0 : getSee_date().hashCode());
        result = prime * result + ((getNoon() == null) ? 0 : getNoon().hashCode());
        result = prime * result + ((getDept_id() == null) ? 0 : getDept_id().hashCode());
        result = prime * result + ((getDoctor_id() == null) ? 0 : getDoctor_id().hashCode());
        result = prime * result + ((getReg_level_id() == null) ? 0 : getReg_level_id().hashCode());
        result = prime * result + ((getSettlement_type() == null) ? 0 : getSettlement_type().hashCode());
        result = prime * result + ((getNeed_case_book() == null) ? 0 : getNeed_case_book().hashCode());
        result = prime * result + ((getReg_time() == null) ? 0 : getReg_time().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getInspection_status() == null) ? 0 : getInspection_status().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}