package org.neu.entity;

import java.io.Serializable;
import java.util.Date;

public class Schedule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private Date arrange_time;

    private Integer dept_id;

    private Integer doctor_id;

    private String noon;

    private Integer schedule_rule_id;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public Schedule withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getArrange_time() {
        return arrange_time;
    }

    public Schedule withArrange_time(Date arrange_time) {
        this.setArrange_time(arrange_time);
        return this;
    }

    public void setArrange_time(Date arrange_time) {
        this.arrange_time = arrange_time;
    }

    public Integer getDept_id() {
        return dept_id;
    }

    public Schedule withDept_id(Integer dept_id) {
        this.setDept_id(dept_id);
        return this;
    }

    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }

    public Integer getDoctor_id() {
        return doctor_id;
    }

    public Schedule withDoctor_id(Integer doctor_id) {
        this.setDoctor_id(doctor_id);
        return this;
    }

    public void setDoctor_id(Integer doctor_id) {
        this.doctor_id = doctor_id;
    }

    public String getNoon() {
        return noon;
    }

    public Schedule withNoon(String noon) {
        this.setNoon(noon);
        return this;
    }

    public void setNoon(String noon) {
        this.noon = noon;
    }

    public Integer getSchedule_rule_id() {
        return schedule_rule_id;
    }

    public Schedule withSchedule_rule_id(Integer schedule_rule_id) {
        this.setSchedule_rule_id(schedule_rule_id);
        return this;
    }

    public void setSchedule_rule_id(Integer schedule_rule_id) {
        this.schedule_rule_id = schedule_rule_id;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public Schedule withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", arrange_time=").append(arrange_time);
        sb.append(", dept_id=").append(dept_id);
        sb.append(", doctor_id=").append(doctor_id);
        sb.append(", noon=").append(noon);
        sb.append(", schedule_rule_id=").append(schedule_rule_id);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Schedule other = (Schedule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getArrange_time() == null ? other.getArrange_time() == null : this.getArrange_time().equals(other.getArrange_time()))
            && (this.getDept_id() == null ? other.getDept_id() == null : this.getDept_id().equals(other.getDept_id()))
            && (this.getDoctor_id() == null ? other.getDoctor_id() == null : this.getDoctor_id().equals(other.getDoctor_id()))
            && (this.getNoon() == null ? other.getNoon() == null : this.getNoon().equals(other.getNoon()))
            && (this.getSchedule_rule_id() == null ? other.getSchedule_rule_id() == null : this.getSchedule_rule_id().equals(other.getSchedule_rule_id()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getArrange_time() == null) ? 0 : getArrange_time().hashCode());
        result = prime * result + ((getDept_id() == null) ? 0 : getDept_id().hashCode());
        result = prime * result + ((getDoctor_id() == null) ? 0 : getDoctor_id().hashCode());
        result = prime * result + ((getNoon() == null) ? 0 : getNoon().hashCode());
        result = prime * result + ((getSchedule_rule_id() == null) ? 0 : getSchedule_rule_id().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}