package org.neu.entity;

import java.io.Serializable;
import java.util.Date;

public class TemplateHerb implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DELETED = true;

    private Integer id;

    private String name;

    private Integer doctor_id;

    private Date create_time;

    private String prescription_type;

    private Integer number;

    private String method;

    private String treatment;

    private String treatment_detail;

    private String doctor_advice;

    private String range;

    private Boolean is_deleted;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public TemplateHerb withId(Integer id) {
        this.setId(id);
        return this;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public TemplateHerb withName(String name) {
        this.setName(name);
        return this;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getDoctor_id() {
        return doctor_id;
    }

    public TemplateHerb withDoctor_id(Integer doctor_id) {
        this.setDoctor_id(doctor_id);
        return this;
    }

    public void setDoctor_id(Integer doctor_id) {
        this.doctor_id = doctor_id;
    }

    public Date getCreate_time() {
        return create_time;
    }

    public TemplateHerb withCreate_time(Date create_time) {
        this.setCreate_time(create_time);
        return this;
    }

    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    public String getPrescription_type() {
        return prescription_type;
    }

    public TemplateHerb withPrescription_type(String prescription_type) {
        this.setPrescription_type(prescription_type);
        return this;
    }

    public void setPrescription_type(String prescription_type) {
        this.prescription_type = prescription_type;
    }

    public Integer getNumber() {
        return number;
    }

    public TemplateHerb withNumber(Integer number) {
        this.setNumber(number);
        return this;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getMethod() {
        return method;
    }

    public TemplateHerb withMethod(String method) {
        this.setMethod(method);
        return this;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getTreatment() {
        return treatment;
    }

    public TemplateHerb withTreatment(String treatment) {
        this.setTreatment(treatment);
        return this;
    }

    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    public String getTreatment_detail() {
        return treatment_detail;
    }

    public TemplateHerb withTreatment_detail(String treatment_detail) {
        this.setTreatment_detail(treatment_detail);
        return this;
    }

    public void setTreatment_detail(String treatment_detail) {
        this.treatment_detail = treatment_detail;
    }

    public String getDoctor_advice() {
        return doctor_advice;
    }

    public TemplateHerb withDoctor_advice(String doctor_advice) {
        this.setDoctor_advice(doctor_advice);
        return this;
    }

    public void setDoctor_advice(String doctor_advice) {
        this.doctor_advice = doctor_advice;
    }

    public String getRange() {
        return range;
    }

    public TemplateHerb withRange(String range) {
        this.setRange(range);
        return this;
    }

    public void setRange(String range) {
        this.range = range;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public TemplateHerb withIs_deleted(Boolean is_deleted) {
        this.setIs_deleted(is_deleted);
        return this;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", doctor_id=").append(doctor_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", prescription_type=").append(prescription_type);
        sb.append(", number=").append(number);
        sb.append(", method=").append(method);
        sb.append(", treatment=").append(treatment);
        sb.append(", treatment_detail=").append(treatment_detail);
        sb.append(", doctor_advice=").append(doctor_advice);
        sb.append(", range=").append(range);
        sb.append(", is_deleted=").append(is_deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_herb
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setIs_deleted(deleted ? DELETED : NOT_DELETED);
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TemplateHerb other = (TemplateHerb) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDoctor_id() == null ? other.getDoctor_id() == null : this.getDoctor_id().equals(other.getDoctor_id()))
            && (this.getCreate_time() == null ? other.getCreate_time() == null : this.getCreate_time().equals(other.getCreate_time()))
            && (this.getPrescription_type() == null ? other.getPrescription_type() == null : this.getPrescription_type().equals(other.getPrescription_type()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getTreatment() == null ? other.getTreatment() == null : this.getTreatment().equals(other.getTreatment()))
            && (this.getTreatment_detail() == null ? other.getTreatment_detail() == null : this.getTreatment_detail().equals(other.getTreatment_detail()))
            && (this.getDoctor_advice() == null ? other.getDoctor_advice() == null : this.getDoctor_advice().equals(other.getDoctor_advice()))
            && (this.getRange() == null ? other.getRange() == null : this.getRange().equals(other.getRange()))
            && (this.getIs_deleted() == null ? other.getIs_deleted() == null : this.getIs_deleted().equals(other.getIs_deleted()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDoctor_id() == null) ? 0 : getDoctor_id().hashCode());
        result = prime * result + ((getCreate_time() == null) ? 0 : getCreate_time().hashCode());
        result = prime * result + ((getPrescription_type() == null) ? 0 : getPrescription_type().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getTreatment() == null) ? 0 : getTreatment().hashCode());
        result = prime * result + ((getTreatment_detail() == null) ? 0 : getTreatment_detail().hashCode());
        result = prime * result + ((getDoctor_advice() == null) ? 0 : getDoctor_advice().hashCode());
        result = prime * result + ((getRange() == null) ? 0 : getRange().hashCode());
        result = prime * result + ((getIs_deleted() == null) ? 0 : getIs_deleted().hashCode());
        return result;
    }
}